### ISSUE TITLE
Ship ID in killmail data

### ISSUE THREAD

**Issue by StephenSwat** [ccpgames/esi-issues#102]
I'm not sure if this information is stored by CCP at all but if it is might it be possible to get the ship ID of attackers and victims in killmails? I mean the unique identifier of an assembled ship instead of the ID of the ship type. Some ships live for a long time in EVE and I think it would add a lot of flavour and character if we were able to track kills on individual ships as well as pilots.

**Comment by Regner** [comment]
I don't know if the information is stored, cannot remember. However storing and sharing the attackers ship ID is something I must strongly suggest NOT happen. To much information can be gained from that, especially if someone is doing bad things with the client.

Adding killmark information to the API would be nice though if it isn't already there.

**Comment by wtfrank** [comment]
On the other hand, if its a *citadel/EC* that's dishing out or taking a beating, it would be very interesting if the id of the structure (which is basically public already) was in the killmail. That way we could have structure killboards...

Currently you don't get a unique identification when a structure appears on a killmail. With a ship, you have the pilot name, but with structures there may or may not be a pilot in the structure and finding out the corp/alliance owner of the structure doesn't uniquely identify it in the same way that finding out the pilot of a ship does.

For those reasons, I reckon having the structure id in the killmail would not do the bad things that a ship id would, and it would allow some new cool 3rd party stuff.

**Comment by rottjr** [comment]
I'm sure this information is stored somewhere (otherwise killmarks wouldn't be a thing) but I'm not sure CCP will begin providing it to developers. I'm not sure it would cause a huge issue unless the developer began making it public (not sure why that would be necessary or why the user would allow it). However even then you're just going to be aware that the player has a ship that consistently wins and hasn't died, would create a new meta-gamer aspect.

I'm not sure citadel id's would be necessary, if I remember correctly it does directly associate the citadel km with a corporation/alliance making it uniquely identifiable. I'm actually implementing a citadel killboard right now. But unlike ships a citadel is a corporation or alliance structure and the isk hit should not be made against the pilot that was in it, could have just been a passer by that jumped in to try and defend it.

**Comment by StephenSwat** [comment]
@Regner Could you elaborate on the information that you could gain from something like this? I'm not saying you're wrong at all, just curious.

@rottjr Concerning killmarks, that might just be a counter stored inside the ship with the number of kills it has; not a list of killmails.

**Comment by rottjr** [comment]
@StephenSwat This is true, however that counter would still be stored in a flat file or cloud style database meaning it is accessible. The biggest problem we come back to is identifying one ship over another. IE: you have two maulers, both named 'Mauler T1' and both with identical fits, how to differentiate? Also, you decide to package one of those ships, what is to happen with the killmark data, simply disable or delete?

**Comment by StephenSwat** [comment]
@rottjr Every assembled in EVE has, as I understand it, a unique number that identifies it. You can access the ID of the current ship of a pilot with [this](https://esi.tech.ccp.is/latest/#!/Location/get_characters_character_id_ship) endpoint. That way you could differentiate two otherwise identical ships. This issue is about including that identifier in the killmail API.

**Comment by wtfrank** [comment]
@rottjr yes the structure is associated with a corp / alliance, but there are a few issues that I have run across while also working on a structure killboard:

1) there can be multiple structures owned by the same corp in the same system, so system+corp alone isn't enough to identify a structure
2) structures can be transferred to different ownership so the corp doesn't even stay constant over time, making this an unreliable method of attributing kills to a particular citadel
3) x,y,z coordinates of where the pilot dies exist in the killmail, and since last week we know the x,y,z coordinates of some citadels (public ones or ones we have access to). So it may be possible to associate some killmails near a citadel to a particular citadel. However if a pilot is shot by a citadel, then warps to a planet where he is tackled by someone and killed, the killmail logs where the pilot dies, but then all we know is that *a* citadel did some damage to the pilot, but we cannot be certain which particular citadel in the system did the damage, therefore can't reliable assign it to a particular citadel.

**Comment by rottjr** [comment]
@wtfrank thanks for the clarification. I agree a unique ID should be assigned to each citadel and made available in Killmails etc. This could also be useful for asset searching etc. if implemented more universally.

**Comment by cvweiss** [comment]
I would love to see this, but I have to agree with @Regner, too much information could be given out.

**Comment by wtfrank** [comment]
Even if it applied to structures only and not ships?

**Comment by antihax** [comment]
It would be nice to have it applied to structures... i agree with the comments about the ship itemID though.

**Comment by cvweiss** [comment]
What if we included only the unique identifier of the destroyed ship? This could assist applications that work with assets and reconcile the location of a now missing asset (e.g. it was destroyed).

Also, +1 killmarks

**Comment by Robbilie** [comment]
i think the victims ship_id would be cool, attackers ids could be used for various tracking stuff, i did some nice stuff with the logserver and tracked someone down using it…
dont see an issue with having the vicitims id though :)

+1 killmarks
+1 skin

**Comment by tsuthers-ccpgames** [comment]
There's a lotta information in here that should probs be over here now: https://github.com/ccpgames/esi-issues/issues/842

The item ID's discussion is interesting, I thought that was already in existing killmails but maybe I'm wrong.
