### ISSUE TITLE
/characters/{character_id}/killmails/recent/ min_kill_id or min_timestamp

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/esi-issues#126]
Please add a minimum id or timestamp parameter to the killlog endpoint
So far the endpoint only has a max_kill_id parameter and will yield all kills prior to that. I think in most use cases we know to what point we have the kills already and want to start from there. Right now I start without max_kill_id which yield the most current ones and then move back until i hit the ones I know already but that makes it unnecessary many calls. This would be even more useful in case of a corporation killmails endpoint, where just getting all of them might be no longer feasible.

Bests,
Snitch

**Comment by polarina** [comment]
How does not having `min_kill_id` result in more HTTP requests than having one?

**Comment by snitchashor** [comment]
If you want to retrieve a set of lets say 500 kills starting with the last known one, right now there is no way of doing this in one call.

**Comment by polarina** [comment]
Making the assumption that you want all killmails more recent than a particular kill here, I do not see how that would result in more HTTP calls.

You start with no `max_kill_id` to `/characters/{character_id}/killmails/recent/` and get the 500 most recent ones. If the killmail you would've otherwise given as `min_kill_id` is in that list, you're done. One request. If not, you need to make another request to get the next 500 killmails, the same you would need to do with `min_kill_id` if there are more than 500 more recent killmails than that.

I don't see how not having `min_kill_id` results in more needed HTTP requests.

**Comment by snitchashor** [comment]
Thats exactly what I meant with more calls, having a min_kill_id removes the step of checking if the wanted id is in the list and making subsequent requests.

**Comment by polarina** [comment]
Don't you still need to loop over the result for processing or inserting into your local database? For each element, you can check if the ID you got is less than or equal to the highest kill ID you got on record, and discard it if so.

**Comment by cvweiss** [comment]
I've implemented complete parsing of the esi killmail endpoint on zkillboard, it isn't that difficult without the min killID as requested by OP.

Your first request, the maximum kill ID in your database should be 0. Begin pulling from the endpoint, as long as the killmail killIDs are greater than your stored max killID, keep pulling using the max_kill_id, maintaining a variable, newMaxKillID. When you're done iterating through all endpoints (e.g., the result size is less than the max requested), update your database record to the newMaxKillID.  Next time you pull, apply the same logic as just outlined and stop making requests when the killIDs in the request are less than or equal to your current maxKillID.

You are requesting the reverse functionality of what already exists. While I'm not opposed to it, just thinking about killID numbers in a different direction (down, rather than up) can solve the same problem.

**Comment by aquarhead** [comment]
I'm closing this for now.

Maybe one day if we refactor how killmails are generated and stored, we can then introduce more ways to filter/traverse killmails.

But for now we want to minimize load impact on EVE servers as much as possible (in this case the amount of cache we have to generate), so we'll stick with this style of traversing a character/corporation's killmail, as we think it's easier to setup for monitoring new killmails while still possible to get all the killmails back to the first one.
