### ISSUE TITLE
Request: corporation endpoint with tax rate history

### ISSUE THREAD

**Issue by sn0opy** [ccpgames/esi-issues#140]
Currently, the only way to get a history of tax rate changes is to retrieve a corporation's member's notifications. Instead, this should be a pure corporation feature to get these changes from the API.

**Comment by CarbonAlabel** [comment]
I'm going to take a wild guess here and say that CCP doesn't store corporation tax changes in pure form either.

A more reasonable request might be to first get the current tax rate added to the corporations endpoint.

**Comment by Mumbleskates** [comment]
Including salient general information like corporation tax rate and character security status, even if it is not logged historically. Newer versions of the API going from XML to CREST to ESI have tended to bleed off this kind of useful information, and I'd love to have it back.

**Comment by Mumbleskates** [comment]
I would recommend change or split this issue: one to provide the missing corporation tax rate at all, and one as a more significant feature request for the full history.

**Comment by sn0opy** [comment]
I'd be okay, if it's included in the public corporation  information
without being cached for several hours.

**Comment by aquarhead** [comment]
We now include `tax_rate` in [corporation info endpoint](https://esi.tech.ccp.is/latest/#!/Corporation/get_corporations_corporation_id).

We won't provide historical records of tax rates because we only store the current tax rate value. But you can try monitor [this](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_notifications.html) (when it has an ESI parity endpoint) to construct a "tax rate history" yourself.

**Comment by sn0opy** [comment]
Thanks for adding it to ESI.

Being able to fetch the corp info every 5 minutes is totally okay to me. The Notifications endpoint requires me to have extra permissions for every single corp I want to fetch data for.
