### ISSUE TITLE
characterId is redundant in Contacts API?

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#177]
characterId should be inherent from the OAuth token and not needed on all ContactsApi calls.

**Comment by polarina** [comment]
Are you referring to the character ID given in the URL?

**Comment by ddouglas493** [comment]
He is. We spoke about this on Slack the other night.

**Comment by polarina** [comment]
That is by design. The SSO data is used strictly only for authentication and authorization purposes. That is, after successfully passing the authorization layer in ESI, the API essentially treats your request as an "all-access" kind of request and thus needs to know which character you want information for.

**Comment by antihax** [comment]
Fair enough. Thought i would ask.
