### ISSUE TITLE
esi-fleets: Trying to kick yourself from fleet gives "Action Failed" 500

### ISSUE THREAD

**Issue by lunedis** [ccpgames/esi-issues#181]
Reproduce:

Open new fleet, invite one other character.
Authenticate with ESI, send a "DELETE" request with the fleet ID and your own characterID.

Result: 
`{
  "error": "Action failed"
}`
Status Code: 500

**Comment by CarbonAlabel** [comment]
Kicking yourself from your own fleet isn't something you can do, in the client or otherwise. You are expected to use the leave fleet functionality instead, though performing that action remotely isn't possible with any of the current APIs.

For reference, trying to perform the same action with CREST produces the following error message, presumably introduced for cases when a fleet superior tries to kick the fleet boss:

```json
{
  "message": "You cannot kick the Boss in your fleet. It wouldn't be right!",
  "isLocalized": true,
  "key": "FleetCantKickBoss",
  "exceptionType": "ForbiddenError",
  "title": "Cannot kick Boss"
}
```

**Comment by polarina** [comment]
@CarbonAlabel this is still a valid bug report. No requests to ESI, valid or not, should result in an "Action failed" error.
