### ISSUE TITLE
ESI Strict Searching returns multiple items when only 1 is expected

### ISSUE THREAD

**Issue by Yantrio** [ccpgames/esi-issues#211]
Issue:
When hitting the search API searching for `Dominix` with the strict flag set to true (https://esi.tech.ccp.is/latest/search/?search=Dominix&categories=inventorytype&language=en-us&strict=true&datasource=tranquility), the api returns 2 results. When looking up the items it returns, one is named `Dominix` and the other is named `♦ Dominix`.

Expected :
I don't think that the `♦ Dominix` item result should be returned by the api with the strict search on.

**Comment by SpeedProg** [comment]
Same thing happens when searching for characters, probably on everything else (corp/alliances) too.
if they have some none ascii? characters in name like '
e.g. character search for Quinthar Tha'yr returns [91908540, 2112563506] being Quinthar Tha'yr and Quinthar Thayr.
This bug makes it necessary to request the whole character data for the returned ids and verify the name against it. When I really only want the id for a name.

**Comment by mullinger** [comment]
The same problem happens to me when searching for corporations.

[ESI QUERY](https://esi.tech.ccp.is/latest/search/?categories=corporation&datasource=tranquility&language=en-us&search=Caldari%20Navy&strict=true)

will return 2 corporation because one corporation is defined as such:

`{
  "corporation_name": "Caldari.Navy",
  "ticker": "CA.NY",
  "member_count": 1,
  "ceo_id": 828066889,
  "corporation_description": "Введите описание своей корпорации.",
  "tax_rate": 0,
  "creator_id": 828066889,
  "url": "http://",
  "creation_date": "2015-07-30T17:33:29Z",
  "faction": "Caldari"
}`

When using the endpoint as ID lookup for known types this is pretty annoying.

IMHO 'strict' is not strict enough here.

**Comment by mullinger** [comment]
I did a few experiments using "strict" search:

special characters such as ._+ seem to be ignored in either input or output when comparing values.
On top of that, search is case insensitive.

Which means:
I can search for "caldari+navY?" and will get the corporations "Caldari.Navy" as well as "Caldari Navy".

**Comment by haggen** [comment]
Do we have any news on this one?

**Comment by tsuthers-ccpgames** [comment]
For the moment, this is intended behavior. The search system exists primarily for human users in the client, the API is merely piggybacking on it. For humans, it's important that queries for:
`'excavator' mining drone` 
and 
`excavator mining drone`
both return results. It's also more friendly for humans if they don't have to care about where the hyphens go in nullsec system names. Fundamentally, search systems are about helping people find the stuff they are after, and being grammar nazis over the queries is not helpful for that. 

We're in the process of doing upgrades to the search system which may allow us to do some filtering for you (and also return the strings of the search results along with the results, wouldn't that be a wonderful world!), but for the moment this is working as intended. We're not going to make the search system less human friendly to save you from doing one or two extra lookups per API call.

**Comment by haggen** [comment]
@tsuthers-ccpgames Thank you for your response. Returning the names along with the IDs would be really helpful. If you could find it in your heart the will (and the time) to make this change I'd really appreciate it.
