### ISSUE TITLE
PI: planets endpoint broken (rare)

### ISSUE THREAD

**Issue by hampld** [ccpgames/esi-issues#222]
`GET /characters/{character_id}/planets/{planet_id}/`

endpoint (latest) { planet_id: 40208920 }. returns 500, parsed_response={"error"=>"Action failed"} 

only happens for one character/planet combination.

**Comment by DavidEdwards** [comment]
Is the error constant? 

Do you get the same error every time you call the Endpoint? If for example, you call it once and get a 500 error, then immediately call it again, do you still get a 500 error?

**Comment by tsuthers-ccpgames** [comment]
Is this happening on a planet that has an extractor with no specified resource for extraction?

**Comment by hampld** [comment]
yes, that's the case

**Comment by tsuthers-ccpgames** [comment]
Ya, I'm pretty sure I see the problem here. I might not be able to solve it without making a breaking change, sadface.

**Comment by hampld** [comment]
ok :/ 
well, fix it in a way that makes sense to you. it's not urgent as this should not happen anymore in my app.

**Comment by tsuthers-ccpgames** [comment]
It's happening because currently the code assumes that no extractor head is ever idle, totally my bad. The breaking change will be to make a bunch of the required fields for extractor heads optional. I'll bump the old version to legacy, so if you're calling the /v1 route nothing should change, but once v2 is out you should obv upgrade to get the fix.
