### ISSUE TITLE
Add boolean to /characters/{character_id}/location/ if character is logged in

### ISSUE THREAD

**Issue by StephenSwat** [ccpgames/esi-issues#261]
Currently, the ESI endpoints cannot show if a character is logged in or not. This is very useful information and I believe it should be added.

Workarounds for now include using CREST (which returns an empty response for offline characters) or using a UI endpoint which is obviously not what they are intended for.

**Comment by frankysaken** [comment]
A small extra on this is that (while it doesn't hurt) there are a lot of calls that you don't want to make if a character is offline because they won't change anyways (say: location, ship, etc).

It's also quite a nice feature to have for corporation management tools to make up statistics on what times are the most active by logged-in count as opposed to killmail-count.

**Comment by a-tal** [comment]
I would like to see this as a separate `/character/{character_id}/online/` endpoint (with its own scope) as being online or not more than likely has multiple use cases

**Comment by gitAskur** [comment]
Porque no los dos?

**Comment by gitAskur** [comment]
Created monolith action get_character_online_states-v1 which will resolve a JSONified list of characterIDs to a dictionary keyed with the characterID and the boolean representation of the characters online state.

Added is_online to the return dict of both get_character_location and get_character_ship - raised minor version to 1 on both actions to reflect the change.

**Comment by gitAskur** [comment]
FRACTAL updated. @a-tal you should be able to develop stuff against the changes there. I have also shoved them into Tuesdays TQ deployment, so this can go live tuesday next week!

**Comment by a-tal** [comment]
re: why not both

because the use case exists that a character may want to let someone else know if they're online or not, but not their location (nor ship). similar to how location and current ship are different scopes for the same reason, this is better suited to be its own scope and its own endpoint.

what I think is probably a more interesting discussion though, is creating a "tracking" scope which would enable all three and significantly reduce requests on some of our lowest cache time routes. that has no precedence though (that I know of anyway), so some discussion might need to be had there.

anyway, will have something for `GET /characters/{character_id}/online` Soon™.

**Comment by gitAskur** [comment]
That's not a problem. With the new 'events' structure we can easily make some 'tracking' category for them that gives them a specific subscription. The tracker itself would just pushing them out at which point we'd just need a prime calls from ESI, subscription to those events and probably a mechanism to periodically reprime in case a message got dropped.

I might as well get on that now as I've yet to actually make catgorized events and need a tracer bullet for that anyway that wont disrupt already established functionality.

**Comment by Risingson** [comment]
+1 on "tracking" scope

**Comment by a-tal** [comment]
closing this in favour of #49

for the reasons stated above online state won't be added to the /characters/{id}/location/ endpoint
