### ISSUE TITLE
convert mailing list ids to names

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/esi-issues#266]
Currently there is no way to convert the recipient_id of a mailing list to a name.
It would be most convenient if that information was added to /universe/names/

**Comment by ddouglas493** [comment]
You can get Mailing List ID to Name conversion from the /character/{character_id}/mail/lists endpoint. 

https://esi.tech.ccp.is/latest/#!/Mail/get_characters_character_id_mail_lists

I don't think there is a need for a global Mailing List Endpoint as the names of the mailing lists are reserved just for the members of the mailing lists

**Comment by aquarhead** [comment]
Just like @ddavaham mentioned, if you received a mail from a mailing list you belong to, you should be able to resolve the name via that character's mailing list endpoint. Otherwise you're not supposed to see name of a random mailing list.

**Comment by SCDrifter** [comment]
@aquarhead
That only works for mailing list that the characters are currently subscribed to. I have mails on my character from mailinglists that I can't get names of because I unsubscribed to them.

**Comment by ErikKalkoken** [comment]
@aquarhead I vote to reopen this issue, since the problem has not been solved.
While its fair that one can no longer see the names of former mailing lists, that also makes it impossible to distinguish them from a character ID. The only way to identify those IDs currently is to sent them to the `/characters/names/` endpoint, and when they fail you know its a mailing list.
Instead the /mail/ endpoint should include a flag in the mail header response indicating that this mail is from a mailing list and not a character, e.g.` from_mailing_list = true`

**Comment by ddavaham** [comment]
So this brings up another issue I opened already

https://github.com/ccpgames/esi-issues/issues/312
