### ISSUE TITLE
Bulk CharacterName->CharacterID endpoint

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#27]
https://trello.com/c/f8h8Aw6D/18-bulk-charactername-characterid-endpoint

**Comment by gitAskur** [comment]
Whoops, should have closed this down a long time ago (or assign it somewhere else).

Action get_character_names-v1 was created some time ago, and fixed to prime things properly some time ago as well, and that's what is sitting out on TQ right now.

**Comment by DaneelTrevize** [comment]
The original Trello link seems invalid, but I fail to see how get_character_names is an implementation of a name -> ID lookup.

ESI says: "Implementation Notes: Resolve a set of character IDs to character names".

Similarly post_universe_names only does the reverse too. Neither offer a bulk replacement for the XML API's /eve/CharacterID.xml.aspx

As per a discussion from ~ the start of Feb when this issue was (mistakenly?) deemed Done soon after.
https://www.reddit.com/r/evetech/comments/5pik01/character_name_api_lookups_in_2017/

**Comment by gitAskur** [comment]
Yup, that's totally me just reading things wrong, turning them around in my head, and closing this as a characterID > characterName request. My bad!

Reopening, pending internal discussions.

**Comment by gitAskur** [comment]
After having looked at this, the potential solutions, spoken with people about their use cases, with @tsuthers-ccpgames about our options and educated a handful of my coworkers about the benefits of democratisizing our markets and economies, much like we democratisized our body politics; we have decided to hold off on ESI implementation until we have launched the new elastic search driven search for EVE.

Reimplementing this as a Monolith side action just as an intermediate step is way too much work that will be undone in a month or three.

As such I am removing myself from this and setting it back to New.

**Comment by CarbonAlabel** [comment]
A quick reminder in case it slipped someone's mind: the `/eve/CharacterID.xml.aspx` endpoint this is supposed to replace isn't only used to translate character names to their IDs; it does the same for corporations, alliances, factions, systems, stations, celestials and just about everything else which has a name.

**Comment by ccp-zoetrope** [comment]
https://esi.tech.ccp.is/ui/#/Universe/post_universe_ids
