### ISSUE TITLE
Request: Add flag to /universe/types/{type_id} indicating whether item can be put on market

### ISSUE THREAD

**Issue by MrNukealizer** [ccpgames/esi-issues#276]
There's currently no way to tell based on ESI alone whether an item can be listed on the market or not. Types in the SDE have a marketGroupID field that can be checked for that purpose. It seems items with a market group can be listed and those without a market group can't.

**Comment by Regner** [comment]
Would recommend adding the market group ID instead. If it had a market group ID then not I do you know it can go on the market but where.

**Comment by MrNukealizer** [comment]
Right, giving the market group ID would be ideal, but then we'd also need a way to get the market groups. I was just suggesting the simplest solution available. I'd imagine a lot more people just care whether they should bother checking orders for an item than those who care what category it's under in the game.

**Comment by Regner** [comment]
The backend should have that information already. You also don't need a way to get the market groups at first. Simple having the market group ID in the response here would accomplish the goal you wanted, to know if it can go on the market, and then later they can add a full listing of market groups.

**Comment by aquarhead** [comment]
I'll look into adding the `market_group_id` in type info, will have the market groups endpoint soon, but I think I'll not port the market types endpoints over, is there any objection?

**Comment by Regner** [comment]
@aquarhead The market types endpoint, going from memory but pretty sure it was that endpoint, was wonderful for the fact that you could filter by a specific market group. Made working with SPAs really nice and just general on the fly stuff really nice as you could load each group one at a time.

That being said with how slow things are probably best to just make one big request and deal with that. Not the end of the world. Was just a "nice" thing. :)

**Comment by aquarhead** [comment]
I currently have an endpoint (in dev) that lists all the market group ids, then in each market group's endpoint I also have the types expanded to all the type_ids under that actual group (comparing this to the CREST market types endpoint's filtering functionality you're talking about, it only shows the types that are directly under that group, e.g. Rifter will not be shown under `/markets/groups/5/` but only `/markets/groups/64/`)

I want to get rid of it mostly because the market types endpoint doesn't really give any more information and it's ultimately the same resource as "inventory" types.

**Comment by Regner** [comment]
Sounds like that is even better. :)

**Comment by aquarhead** [comment]
`/v3/` deployed.
