### ISSUE TITLE
Broken link at developers.eveonline.com

### ISSUE THREAD

**Issue by biow0lf** [ccpgames/esi-issues#284]
In resources section link "YC-119-2_1.0_Types.zip" points to "http://content.eveonline.com/data/YC-119-1_2.0_Types.zip" which are looks broken. Should it be http://content.eveonline.com/data/YC-119-2_1.0_Types.zip ?

**Comment by tsuthers-ccpgames** [comment]
This has been fixed today. However, this is not the right place for reporting non-esi issues, and this took a lot longer to resolve than it should have because the team that needed to see it doesn't work on ESI so they don't check this board. Please use the bug reporting tool for all non-esi issues.
