### ISSUE TITLE
Sec status on character profile

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#33]
https://trello.com/c/9UnjTo4J/24-sec-status-on-character-profile

**Comment by tsuthers-ccpgames** [comment]
completed

**Comment by Mumbleskates** [comment]
This is not yet appearing on dev, is it pending the next release?

**Comment by sn0opy** [comment]
@Mumbleskates Right now, Dev, Stable and Legacy are pretty the same since ESI isn't feature-ready yet. Releases happen like every few hours right now.

**Comment by Mumbleskates** [comment]
Okay. I find it even more odd then, that a feature declare to be done ten days ago isn't reflecting anywhere I can see.

**Comment by tsuthers-ccpgames** [comment]
Looks like we tripped over an edge case in the endpoint versioning system and it got hidden, good catch. 

I've committed a patch, I need to check in with @a-tal before I push it out, because he was doing some work on the underlying framework over the weekend and I don't know where he got with that. Soon™.

**Comment by tsuthers-ccpgames** [comment]
aaaand it's back!

**Comment by Mumbleskates** [comment]
Great.
