### ISSUE TITLE
/markets/{region_id}/orders/ returns buy orders in Citadels

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#361]
The GET /markets/{region_id}/orders/ endpoint returns buy orders from Citadel structures.

For example https://esi.tech.ccp.is/v1/markets/10000002/orders/?type_id=29668

I'm using no authorization and if I understood closed issues on the same topic correctly, this endpoint should not return orders in Citadels.

It is also impossible to get information on the structure with the same level of authorization (none), as /universe/structures/{structure_id}/ requires the read_structures scope.

**Comment by fuzzysteve** [comment]
They should be.

They return _ranged_ buy orders from citadels. Not orders which are only for the citadel.

This is to match in game functionality, so you can see orders which you can sell to, even if you can't dock in that structure.

**Comment by Ionaru** [comment]
Which is a pretty nice feature, I agree. But then I'd like to actually get some _information_ about the structure, which system it is in, for example.

**Comment by deadlybulb** [comment]
The universe structures endpoint will allow you to look up that information for some citadels (e.g. public citadels).  However, that endpoint requires authentication.  You've also stumbled on at least one inconsistency in the ESI which is that you'll see ranged orders for some non-public citadels which you won't be able to look up in the universe structures endpoint.  Currently, many players turn to a 3rd party source like https://stop.hammerti.me.uk/api/ to resolve non-public citadel data.

**Comment by tsuthers-ccpgames** [comment]
This feature actually originated as an ascended bug in crest, that was created when these orders were exposed in the game client to prevent "shadow buy orders". When citadels were first released, it was possible to create region-wide buy orders with a competitive bid in a private citadel. Because the citadel was private, no one could see your bid, but it was still valid, and so you scooped all the sell orders and no one could see why. That was solved by making all ranged citadel buy orders visible, but this was done to make the price data available, not the location data.

Anyway, that started showing up in crest as well due to the nature of the bug fix, and we elected not to remove the data from crest because it served the same purpose there. We then ported forward to ESI to match functionality. However, we are extremely cautious about giving out information about citadels, and it's important that you understand these orders are included to give you information about the currently most competitive bids price, not it's location. 

If you're authorized to know more information about the citadel, you can use the structure id provided by the market data to hit up /universe/structures/{structure id}/ and get the location. If the auth check on that fails, then the citadel owner doesn't want you to know where their citadel is, and we respect their wishes. You're welcome to make educated guesses or use third party aggregators, but we won't directly confirm or deny :)
