### ISSUE TITLE
/universe/names failed to parse location_id

### ISSUE THREAD

**Issue by heeboA** [ccpgames/esi-issues#418]
# Bug

The names API fails to parse location ids that are too long, returning an error.

### Request

This request fails
`
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[1023257513048]' 'https://esi.tech.ccp.is/latest/universe/names/?datasource=tranquility'
`

While this one succeeds
`
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[60003760]' 'https://esi.tech.ccp.is/latest/universe/names/?datasource=tranquility'
`

### Response

Error response
`
{
  "error": "failed to coerce value '1023257513048' into type integer (format: int32), too few items for 'ids', 'ids' is required"
}
`

### Expected

Expected to get something like
`
[
  {
    "id": 1023257513048,
    "name": "<name>",
    "category": "station"
  }
]
`

**Comment by Robbilie** [comment]
That's a citadel Id no?

**Comment by itshouldntdothis** [comment]
Confirming citadel id, due to `/universe/names/` not supporting citadels expected response would be
```
{
  "error": "no valid IDs found"
}
```
with 404 status code.

**Comment by ddouglas493** [comment]
According to the Spec this is not a bug but intended behavior. 



```
Implementation Notes
Resolve a set of IDs to names and categories. Supported ID's for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.
```
[POST /universe/names/](https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names)

Location IDs don't just reference structures, especially in the case of Assets, they can reference containers and ships.

This should be a feature request to add this functionallity, but I doubt it would be added since the endpoint [GET /universe/structures/{structure_id}/](https://esi.tech.ccp.is/latest/#!/Universe/get_universe_structures_structure_id) exists for this exact case.

This issue can probably be closed.

**Comment by ddouglas493** [comment]
I would like to add a reason to that error message, like "no valid IDs found. ID to long", or "no valid IDs found. ID to large". I had this issue when EVEMail.Space was being developed

**Comment by heeboA** [comment]
"Response Class (Status 200)
List of id/name associations for a set of ID's. ID's that cannot be resolved are not returned."

I'd say this is not expected behaviour, as it should still return a list of resolved ids, not an exception. Also if another api gives out a location id it should then specify the type maybe? Still, how could i know which ids are citadels and other things not supported by universe/names?

**Comment by a-tal** [comment]
this is intended behaviour. to explain though, you've received three errors in the response:

1) `failed to coerce value '1023257513048' into type integer (format: int32)`

you provided '1023257513048' for a parameter that ESI could not coerce into its spec (because in this case, the integer provided was too large for int32)

2) `too few items for 'ids'`

the ids parameter is an array, and the request does not have the minimum items required for it

3) `'ids' is required`

the parameter ids is a required parameter, and has not been satisfied (and no default is specified)
