### ISSUE TITLE
add last login and last logout to /characters/{character_id}/online/

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#424]
# Feature request

### Route

v2 /characters/{character_id}/online/

### Authentication

esi-location.read_online.v1

### Example returns

```json
{
  "online": true,
  "last_login": "2017-01-02T03:04:05Z",
  "last_logout": "2017-01-02T04:05:06Z"
}
```

**Comment by gitAskur** [comment]
Out on Fractal now @a-tal , removing myself from ths!

**Comment by a-tal** [comment]
this is out now. available as /v2/ aka /dev/. need to schedule a move to latest at some point

http://esi.tech.ccp.is/dev/#!/Location/get_characters_character_id_online

**Comment by gitAskur** [comment]
I messed up on this one and moved it to staging without moving code from our sandbox to staging. So the relevant TQ code is not available. I'll get it out ASAP but since we´re rebasing our staging branches in a few hours, in preparation for EMILY, I'll have to talk to some people.

Sorry about this!

**Comment by gitAskur** [comment]
(Stuff is actually in staging now)

**Comment by a-tal** [comment]
this is completed, added number of logins as well. full model:

```
get_characters_character_id_online_ok {
last_login (string, optional): Timestamp of the last login,
last_logout (string, optional): Timestamp of the last logout,
logins (integer, optional): Total number of times the character has logged in,
online (boolean): If the character is online
}
```
