### ISSUE TITLE
Market region does not include orders in citadels

### ISSUE THREAD

**Issue by Zyles** [ccpgames/esi-issues#441]
# Bug

https://esi.tech.ccp.is/latest/#!/Market/get_markets_region_id_orders does not include orders in citadels.

When I list order for an item in Jita I get Perimeter listings in game, but not in the API.

There is a structure order endpoint it seems, but how would I know there is an order of this item in that structure if I can not see it in the response?

# Feature request

1. See orders in structures in the orders endpoint
2. Be able to configure jump range like in the client

### Route

https://esi.tech.ccp.is/latest/#!/Market/get_markets_region_id_orders

### Use case

Be able to see highest order in the region and within X jumps, not just in NPC stations.

If the issues is auth check for citadels. You could make the route show listings with citadels if you have a token (optional).

Your backend servers should know all the citadels which have orders for specific item, even if you do not show them in the public cache.

If there is a token merge the request with public cache and https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id for the citadels you have access to, or give a list with structures that have orders for type_id so we can query them ourselves.

Your API server should be able to make a batch append request internally.

**Comment by GeorgeDietrich** [comment]
Pretty sure this is working as intended.  (think you can only get buy orders from structures from that endpoint?).  

For structure related data you need to be able to access that structure using this endpoint:
https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id

**Comment by Blacksmoke16** [comment]
Pretty sure this is working as intended. (think you can only get buy orders from structures from that endpoint?).

For structure related data you need to be able to access that structure using this endpoint:
https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id

**Comment by Kyria** [comment]
You can see ranged buy orders from upwell structures, but that's all. Mostly because of ACL and caching. 
For structures, you'll have to use the structure endpoint, to know if there are orders, and to know what are the prices. 

See #227 for example (there are others probably too)

**Comment by Zyles** [comment]
Working as intended yes. Good design? No.

In order to get orders from a structure:

1. You need to know the order exists
2. You need to know which structure to look at

Hitting the orders endpoint you do not get any of these things.

I don't see why they can't merge the JSON with the public cache really. The cache would still be in effect.

The backend knows all orders for type X, even if they are in a citadel or not. When creating the public cache the citadel orders are removed right?

When a user queries the order endpoint and they use a token, they can merge that public cache JSON with the citadel data in the backend.

**Comment by Robbilie** [comment]
about your 1., how does this not apply to the normal market? i mean you just fetch and see if there are orders, thats the way it is, everywhere.

about 2., yeah, you usually do that with the public structures endpoint if you want to have a public service, otherwise you can use the search to search for structures or use it to crawl for structures.

**Comment by Kyria** [comment]
Nothing prevents you from saving the structure(s) IDs you want to look at and only get from these, like you probably do for jita. (it's just easier to find jita, since it's a static data from the game). 

If you read the link i've given above, you'd probably understand why CCP can't cache the way you ask, because public and authed cache are not the same : 
> Unfortunately, adding an authentication mechanism breaks our caching strategy for the market/region_id/orders endpoint. Caching is global for non-authed endpoints or per-auth-token for authed routes.

Also how can you tell it's a "bad design", when you don't even know what implies the cache mechanism behind ESI ? On paper sure it's easy to do what you say, like everything, but reality is not always like paper. 

If you want to debate this, the tweetfleet slack is a better place for this.

**Comment by QuakeIV** [comment]
I can confirm that this is extremely unfortunate.  API requests are fairly slow on an individual bases (on the order of like 200 miliseconds at least even for the shortest requests).  If I had to save every citadel structure ID and look up all of the citadel markets individually, this would be extremely slow due to the sheer number of citadels.

I used to have to make individual requests to find the security level for stations so I would know the security level of market orders.  This took around an hour in total on my internet.  I cant imagine citadels would be much better.  My market analysis tool would be greatly improved if I could fetch citadel orders in big batches like I can with stations.  As it is I pretty much cant incorporate citadels in the analysis.

**Comment by polarina** [comment]
@QuakeIV have you considered executing your ESI requests in parallel?

**Comment by QuakeIV** [comment]
Oh hey good idea.  Yeah I guess I'll have to just do that.  Would still be nice to not need to though.

**Comment by QuakeIV** [comment]
Update, threading is more or less working, however the fastest time I saw was 85 seconds.  I can only dispatch about 50 threads or so before I start getting large numbers of timeouts.  This kindof made me feel like I was flooding the server, so I staggered the thread startups by a tenth of a second each to slightly smooth the load.  This didn't end up letting me dispatch any more threads however.

At this point I think I can say fetching these things by batch would probably be better.  85 seconds isn't that bad, but it does kindof suck, and I think the request spam is beating up on the servers.

Also, does anyone have any suggestions for thread startup staggering?  I am not overly familiar with networking, and would like to try to be a good citizen here to some extent.

**Comment by mullinger** [comment]
My app loads a list of all structures every ~1-2 hours and then updates my internal list of existing structures (Cache times are ~ 1h).
Structure count is currently around 3500 if I remember correctly.

I plan on updating structure orders every 5-10 minutes and store results in my app, together with the region orders they are in. This depends on how fast my workers can get all the data. I would advise against using more threads than 2 or 3 times the number of cores of your processor.

In my experience ESI is pretty fast in its answers. 
You *need* to do caching locally and not rely on ESI answers for every client request, basically answer client requests from your own local cache. Check the "expires"-headers in the ESI-replies and don't do the same ESI-request before the cache expires. 
This will help you save a lot of requests

This way I am planning to store ALL orders universe wide in my app and be able to selected orders for clients very fast without having to rely on ESI.

**Comment by aquarhead** [comment]
We will not merge/duplicate public cache-able content with authed content.

Client is able to do auth check for market orders because it has a session attached (always authed). API is not client and does not pretend to be one.
