### ISSUE TITLE
Resolve location_id to structure name for non-freeports with ranged buy orders

### ISSUE THREAD

**Issue by ETristram** [ccpgames/esi-issues#450]
# Feature request
As per design /markets/{region_id}/orders/ returns also ranged buy orders from structures. However ESI only returns a location_id. If the structure is not a freeport, then there currently seems to be no way to retrieve the structure name and solar system.

However in the ingame market browser the name and system of ranged buy orders of non-freeport structures are exposed. Thus this should be possible via ESI as well.
CREST returns the structure name in the respective region order endpoint.

The name can either be added to the region order endpoint or the structure info endpoint returns at least the name and system if a ranged buy order exists. Or the names search endpoint returns the name. Or...

This is related to #65 and #191 

### Route
/markets/{region_id}/orders/ 
OR /universe/structures/{structure_id}/ 
OR /universe/names/ 

### Authentication
No

**Comment by wtfrank** [comment]
Although this is not a solution, as a work-around you can use CREST to get the name as the equivalent CREST call includes it (although it seems to take a while for structure name changes to propagate to CREST).

Also third party API https://stop.hammerti.me.uk/api/docs/structure lets you query the name of a citadel (it has any citadel that has turned up in ESI/CREST, and others).

**Comment by ETristram** [comment]
Thanks, via CREST is exactly how https://www.adam4eve.eu lists and works with structures at the moment. Was exploring if a migration to ESI is viable, but apparently not fully possible yet.

**Comment by AfroHorse** [comment]
I've also bumped into this problem and it looks like I will need to use CREST in the short term even though the rest of my app uses ESI. The other option that would save at least one ESI call in my case (and potentially give away less information) would be to add the solar_system_id of an order onto the response from the region order endpoint

**Comment by ETristram** [comment]
As feature parity has been announced for ESI against XML and CREST I'd be interested how this in-parity has been resolved?
AFAIK there is still no ESI-way to get the name of a non-freeport structure that is being exposed by ranged buy orders. The structure endpoint returns "access denied" and the order endpoint only returns the location ID. CREST supplies the name (and with it the solar system).

If CREST is deactivated in May and this is not fixed then tools like A4E won't be able to display the location of such a ranged buy order in contrast to the ingame market browser.

**Comment by Chnkr** [comment]
#482 would also be nice to have when this is fixed

**Comment by ETristram** [comment]
The cut-off date of CREST is approaching rapidly and 3rd parties also would need a lead time to integrate an offered solution for this issue. Is there any estimation if and when a solution would get available?

**Comment by GoldenGnu** [comment]
I think it’s pretty safe to say that this will be worked on soon. There are only 3 parity issues left, two which are already in progress and then this one being the third. Ofc. I’m not from CCP, so it’s just an assumption...

**Comment by ETristram** [comment]
More than a month later now and CREST shutdown just over a month to go. Thus again the question, if there is any estimation if and when a solution will be available? Developers would also need some (free) time to implement it...

**Comment by ccp-zoetrope** [comment]
This is currently being actively worked on.

**Comment by ccp-zoetrope** [comment]
The solution that was decided upon was to add `system_id` to all orders in `/market/{region_id}/orders/`. We will not however be returning the name of the given structure. The reason for not returning names has a slight bit of history....

Last year we fixed ghost market orders by allowing clients to see all ranged buy market orders even if the character doesn't have docking rights, which implied letting people see the structure name. That fix accidentally enabled the same information in CREST, and we decided to leave it there because at the time structure names weren't strategic information. About a month after that change went out structure names were changed to include solar systems, so API access to this information was never really considered in light of structure names giving out structure locations.

In ESI we want to hold a fast line against giving out info about structures a user does not have docking rights to. However, not being able to know the solar system that an order originates from is definitely a problem because it means you can't tell if you're beating all orders that overlap your order via the API. You can also not tell where to fly to if you want to sell the given order.

Therefore, the solution we decided on is not to return structure names but instead to return the `system_id` every order is placed in, since we believe the need for the name was mostly to determine the solar system anyway.

**Comment by ETristram** [comment]
Is the handling changed ingame as well? Because currently AFAIK you see in the market browser both location and name of the structure with a ranged buy order even if you don't have docking access. Thus no ghost orders anymore.

If ESI doesn't allow to resolve the name, just the location then 3rd party market browsers are at a dis-advantage and have to use a place-holder like "Undisclosed structure ID XYZ in system Perimeter" from May forward.

In my opinion if a structure owner equips a market module, he has to be aware of the risk, that the structure is exposed by ranged buy orders and has to handle that risk.

**Comment by ccp-zoetrope** [comment]
This is true that you can see the structure names in the client, but you can only see them for a particular region at a time. We are trying to not have a side channel that helps people to unfairly get a cluster wide view about structures and this would do exactly that. The API has the advantage of being able to quickly get ALL region market orders and exposing structure names through that would mean that this route would end up being used for scanning for structures, not for its intended purpose.

**Comment by ccp-zoetrope** [comment]
`system_id` has been added to [/v1/markets/{region_id}/orders/](https://esi-test.evetech.net/ui/#/Market/get_markets_region_id_orders).
