### ISSUE TITLE
User Interface endpoints should be under the character endpoint

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#455]
# Inconsistency
The process of checking if you are authorized to make a request should not imply the character_id, instead get it from the path like for other authorized endpoints (example: mail, contacts).

### Routes
/ui/*

### Resolution
move them to /characters/{character_id}/ui/*

**Comment by ddouglas493** [comment]
Can you elaborate on this? The UI Endpoints do not interact with character data, which is what the character category is for.

**Comment by Robbilie** [comment]
I don't want it to be added to the character tag if that is what you are referring to with category. Nowhere in the request the character for which the action is executed can be found which should not happen. OAuth should only verify and not supply the character not should the request have state by getting the id in the Backend from the oauth authorization server.

**Comment by aquarhead** [comment]
All the remote UI operations are 1. POST in the sense of HTTP verbs 2. just tries to send a message to the client with no return

There's nothing to cache, there's no need to require a `character_id` in path and double check that against the token.

Also, they are actually acting on a "client connection" rather than a character resource or sth. They are simply not RESTful in any sense at all.
