### ISSUE TITLE
add faction_id for faction war alliances

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#46]

**Comment by gitAskur** [comment]
The definition of an alliance being a part of facwar is "All the corps in the alliance are a part of facwar" rather than the alliance itself being any part of it. This probably creates a lot of silly side effects like corps that join the alliance after it enlists and so and so.

I've added the factionID as a nullable return key for the monolith event get_corporation_info-v1 (minor 1).

Also added the url in the same minor version increment but that's got nothing to do with anything.

**Comment by Robbilie** [comment]
aka there will be no faction_id on alliances right?
if a corp is in FW and in an alliance we can assume the alliance is in FW too…?

**Comment by gitAskur** [comment]
There is no faction_id on alliances. We could either provide one in a derived manner, or just give you the corp factionID and tell you that your assumption holds. I'll have to look at the code before I can ack that though and honestly I do not expect that to be true.

But maybe! More on this later!

**Comment by gitAskur** [comment]
Aaaaaand two weeks later I get around to check this and will add a derived faction_id to the alliance endpoint based on my findings.

**Comment by gitAskur** [comment]
@Robbilie until those changes make it anywhere you can assume that if any corp in an alliance is in facwar the entire corp is in facwar for that fac.

**Comment by Robbilie** [comment]
forgot to reply, not doing anything with it atm, just wanted it to not be forgotten :)

**Comment by a-tal** [comment]
https://esi.tech.ccp.is/ui/?version=dev#/Alliance/get_alliances_alliance_id
