### ISSUE TITLE
add to /universe/names/ planet, moon, star gate

### ISSUE THREAD

**Issue by Ekzilit** [ccpgames/esi-issues#472]
In response from /universe/systems/{system_id}/ we have ids for planets, moon, starGates
I see only one way to get names for them - using
/universe/stargates/{stargate_id}/
/universe/moons/{moon_id}/
/universe/planets/{planet_id}/

Process of getting information about 1 system takes ~10 seconds

it wiil be great to have ability to get names for them from  "/universe/names/".

**Comment by BBrey** [comment]
Or just go with the right way and have /planets, /moons, /stargates just return the names.

**Comment by itshouldntdothis** [comment]
@BBrey Not sure what you mean as all three of the endpoints you listed currently return the name and the feature request was to allow these id's to be resolved to names via the names endpoint.

Hopefully you might clarify are you in support of this feature request or do you feel that the names should be resolved by calling the individual endpoints rather than the bulk names endpoint?

**Comment by BBrey** [comment]
@itshouldntdothis of course I am in favor of resolving all names of objects through a the universe/names endpoint. If ccp want to have the developers work that way, all id's should be resolvable there.

The function getCharactersCharacterIdPlanets only returns id's for example. So I have to call de planet/{planet_id}  to get the names.

**Comment by CarbonAlabel** [comment]
These requests and more are now included in #736.

**Comment by ccp-zoetrope** [comment]
Celestials will not be added to /universe/names/ at this point in time as described in [this comment](https://github.com/ccpgames/esi-issues/issues/736#issuecomment-375705721) on the issues @CarbonAlabel mentioned above.
