### ISSUE TITLE
[Feature Request] The ability to query sovereignty information on a single system.

### ISSUE THREAD

**Issue by rollo1002** [ccpgames/esi-issues#480]
# Feature request:  The ability to get sovereignty from a single system.

### Example returns 

 "system_id": 30002105,
    "alliance_id": 99005959,
    "corporation_id": 98472414

### Previous XML or CREST route

https://crest-tq.eveonline.com/solarsystems/30002105/
It used to be part of the solarsystem api in the crest. 
"sovereignty": {"id_str": "99005959", "href": "https://crest-tq.eveonline.com/alliances/99005959/", "id": 99005959, "name": "Off The Reservation."}

**Comment by aquarhead** [comment]
This is all in https://esi.tech.ccp.is/latest/#!/Sovereignty/get_sovereignty_map

**Comment by rollo1002** [comment]
I just tried to use this and in order just to get 1 system's information it's taking me 1:11 minutes. This is due to the fact that I have to go through the entire sovmap to include wormhole systems which are not even ownable to search for the one match. The performance hit on the client end is horrendous. This information used to be part of the solar system information why can't you repeat the process?

**Comment by aquarhead** [comment]
Due to the limitation of swagger spec, we can only provide the response in an array, but you can easily reformat the response to a hash or dict which could perform way better for random access.

Reason to not include it as in CREST:

1. We don't want to repeat information in different endpoints which might possibly mismatch due to cache timers
2. All other information in the solar system endpoint is static data and by removing this only dynamic data (which is already presented in another endpoint) we can leverage better cache support such as [ETag](https://www.wikiwand.com/en/HTTP_ETag)
