### ISSUE TITLE
End point universe/structures/ request

### ISSUE THREAD

**Issue by Grasume** [ccpgames/esi-issues#510]
# Feature request
I would like to get a universe/structures/{station_id} . 
This endpoint would act like GET /universe/stations/{station_id} with out needing the Authentication that the current endpoint has and would give basic information about the Structure. Currently there is no cache option or anything with current endpoint /universe/structures/{structure_id}/ (with auth token).
The endpoint would only give out public information on the Structure.

### Route
universe/structures/{station_id}

### Example returns
"application/json": {
    "max_dockable_ship_volume": 50000000,
    "name": "Jakanerva III - Moon 15 - Prompt Delivery Storage",
    "office_rental_cost": 10000,
    "owner": 1000003,
    "race_id": 1,
   "station_id": 60000277,
   "type_id": 1531

}

**Comment by GeorgeDietrich** [comment]
the /universe/{structure_id}/ requires authorization for a reason.  If you do not have access to a structure you would not even know it exists.  i.e. it wouldn't show up in search, overview, right click etc.  Only way to get info about it would find it in system.  

As such there would be no public information about it.

**Comment by Blacksmoke16** [comment]
the /universe/{structure_id}/ requires authorization for a reason. If you do not have access to a structure you would not even know it exists. i.e. it wouldn't show up in search, overview, right click etc. Only way to get info about it would find it in system.

As such there would be no public information about it because it is not public.

**Comment by tsuthers-ccpgames** [comment]
Blacksmoke nailed it :)

**Comment by Grasume** [comment]
The issue is more complicated then this as : When someone uses the https://esi.tech.ccp.is/latest/characters/'. $CharacterId .'/assets/ they will get All assests in the game. Currently when using the location_id you need to go through universe/structures/ , universe/stations/ and keep the SDE staStations in a data base. Now just doing stations is quick but as soon as i go to the universe/structures/{station_id} endpoint it takes 10x longer As well from time to time `403 Forbidden` response: {"error": "Forbidden"} particular 1024774249181 .

**Comment by Grasume** [comment]
So by the Logic of assets you would have access to the structure but not necessarily docking rights to that structure.

**Comment by Blacksmoke16** [comment]
Having assets in a citadel shouldn't give you permission to get the full details of that structure.

I imagine it would be quite challenging on CCP's end to conditionally grant SOME details of it IF you have assets there.  Because of this if you lose access to a citadel, then in terms of ESI, you no longer have access to view its details even if you have assets there.  

This is a unique situation however.  Some discussion/thoughts on CCP's end about this wouldn't be a bad idea.

What you could do then is skip records that you do not have access to:
- Skip them.
- Set the structure to a default with a name like 'Unknown' so the record/item will still be there but you just won't know where/who owns it etc via ESI.
