### ISSUE TITLE
Some star_ids from /universe/systems/{system_id}/ return "Star not found"

### ISSUE THREAD

**Issue by JimmyRoth** [ccpgames/esi-issues#532]
# Bug
/universe/systems/{system_id}/ returns star_id, but /universe/stars/{star_id}/ returns "Star not found"

SolarSystemId, SystemName, StarId
- 30015042,Akhwa,40338201
- 30025042,Annad,40338401
- 30035042,Chaktaren,40338601
- 30045042,Conoban,40338801
- 30013489,Deepari,40339001
- 30023489,Fora,40339201
- 30033489,Hanan,40339401
- 30043489,Horir,40339601
- 30011672,Kerepa,40339801
- 30021672,Pasha,40340001
- 30031672,Safilbab,40340201
- 30041672,Seitam,40340401
- 30011407,Akiainavas,40340601
- 30021407,Aokannitoh,40340801
- 30031407,Hitanishio,40341001
- 30041407,Ichinumi,40341201
- 30011392,Jouvulen,40341401
- 30021392,Kappas,40341601
- 30031392,Komo,40341801
- 30041392,Laah,40342001
- 30010141,Sakenta,40342201
- 30020141,Senda,40342401
- 30030141,Uitra,40342601
- 30040141,Urhinichi,40342801
- 30015305,Adallier,40343001
- 30025305,Channace,40343201
- 30035305,Clacille,40343401
- 30045305,Clellinon,40343601
- 30024971,Hecarrin,40344001
- 30034971,Henebene,40344201
- 30044971,Mesokel,40344401
- 30012715,Odotte,40344601
- 30022715,Oirtlair,40344801
- 30032715,Olelon,40345001
- 30042715,Trossere,40345201
- 30013410,Abrat,40345401
- 30023410,Embod,40345601
- 30033410,Erego,40345801
- 30043410,Fildar,40346001
- 30012547,Hadaugago,40346201
- 30022547,Krilmokenur,40346401
- 30032547,Larkugei,40346601
- 30042547,Loguttur,40346801
- 30012505,Malukker,40347001
- 30022505,Orgron,40347201
- 30032505,Todeko,40347401
- 30042505,Usteli,40347601
- 31000188,J150818,40360504
- 31000316,J105013,40367272
- 31000491,J104210,40376449
- 31000599,J142918,40382327
- 31000604,J232305,40382486
- 31000692,J222830,40386841
- 31000765,J112558,40390928
- 31000909,J123303,40398467
- 31001091,J170409,40407662
- 31001336,J124207,40420403
- 31001457,J142923,40426993
- 31001502,J172915,40429183
- 31001513,J115026,40429643
- 31001586,J102844,40433355
- 31001684,J100107,40438245
- 31001706,J141104,40439253
- 31001709,J215101,40439356
- 31001766,J110915,40442410
- 31001790,J113453,40443452
- 31001796,J103538,40443713
- 31001813,J111617,40444727
- 31001908,J151057,40449525
- 31002422,J103400,40456051
- 31002445,J112417,40456498
- 31002231,J111249,40464240
- 31002241,J145825,40479597
- 31002170,J110841,40483179
- 31002144,J172937,40485464

**Comment by tsuthers-ccpgames** [comment]
A quick check tells me these /are/ stars, must be a problem in the ID checker.

**Comment by tsuthers-ccpgames** [comment]
So it turns out these stars have no statistics for some reason. If you fly to them in game and show info, you'll find they have no age or spectral class etc..

Looks like they've always been this way, I'm asking around for why, hopefully we can get some stats generated for them.

Anyway, that throws an error which then hits an unnecessarily enthusiastic catch statement, and the catch statement assumes all errors indicate you requested something that isn't a star. If for some reason we can't get some stats generated for these fellas I'll make the catch statement a little less enthusiastic, but that solution means that half the attributes on stars will have to become optional, which is pretty weird, so I'd rather fix the underlying data.

**Comment by tsuthers-ccpgames** [comment]
I've generated data for these stars and checked it in, these errors will go away once it flows through our branch structure to TQ. It'll probably take a week or two to get there, but no supervision is required, so I'm closing this as done.
