### ISSUE TITLE
Bug: character wallet transaction does not show transactions using corp wallet

### ISSUE THREAD

**Issue by AOBMarvin** [ccpgames/esi-issues#539]
Since the 28th of August wallet transaction endpoint not returning expected results.  Wallet Journal returns expected results with same character ID and token.

Receiving the following

Response Body
[]
Response Code
200

**Comment by aquarhead** [comment]
Can you give a character ID that is having this issue?

**Comment by AOBMarvin** [comment]
Sure the character ID with this issue is 1029260704

**Comment by AOBMarvin** [comment]
Tested this again now returning results where is_personal is True.  Still not showing any where is_personal is False.

**Comment by aquarhead** [comment]
@a-tal changed this behaviour a while back. Now boolean fields will be omitted if the value is `false`. Looking at the spec, maybe we need to mark all boolean fields as optional, or rethink how this should work. Will talk to @a-tal later.

**Comment by aquarhead** [comment]
Had a chat with @a-tal , apparently I misunderstood a bit there. We only omit `false` boolean field if it's optional, if it's a required field we will keep all boolean fields. So that's not a problem.

@AOBMarvin are you talking about transactions you made using corporation wallet is not shown in the API? (I did a bit testing and it seems that's the case) Those do show in the client. If that's the problem I'll change the title and fix things.

**Comment by AOBMarvin** [comment]
Hi yes it's now just transactions made using the corporation wallet that are not being returned.  Thx

**Comment by gitAskur** [comment]
Let's take a look at this then!

**Comment by aquarhead** [comment]
It's showing now, but seems it also breaks the `is_personal` flag, now all of them are `false`, looking into it now.

**Comment by aquarhead** [comment]
Confirmed this is fixed for an example character, @AOBMarvin can you check whether everything works as intended now?

**Comment by AOBMarvin** [comment]
Looks great - thanks much appreciated
