### ISSUE TITLE
Support "Accept-Language" header

### ISSUE THREAD

**Issue by copyliu** [ccpgames/esi-issues#56]
With CREST, we can send an "Accept-Language" header to specify which language we want the response to be in, CREST would also respond with a "Content-Language" header. 

Currently ESI is missing support for these headers.

**Comment by aquarhead** [comment]
![image](https://cloud.githubusercontent.com/assets/222272/20180586/f6de0db8-a752-11e6-9867-edf91b96d128.png)

**Comment by polarina** [comment]
Would it not make sense to have the relevant endpoints accept a query parameter with the wanted language? The `/search/` endpoint does that, for example.

**Comment by Robbilie** [comment]
relevant = all that contain static data

**Comment by polarina** [comment]
Another approach is to list all language variants in the result set.

```yaml
name:
    en: Hello
    fr: Bonjour
    ja: こんにちは

**Comment by a-tal** [comment]
won't someone think of the bandwidth? ;)

adding more query params where useful is the easy/quick path... and yeah there is some precedent with `/search/` already.

currently ESI doesn't really make use of incoming headers other than auth. sort of want to keep it that way, but if someone can convince me otherwise...

**Comment by Regner** [comment]
I don't suppose the industry standard is convincing enough? Browsers already send that header by default which means when building a client side application that calls the API directly you don't have to do any work and those clients just get the UI in their language.

**Comment by a-tal** [comment]
that's actually why this is tagged with `esi-lib`. I think it's likely clients will send it anyways. debating if this should be a toggle on each route, maybe with a default True for documentation.

**Comment by CarbonAlabel** [comment]
My thoughts on the three (so far) suggested approaches:

#### Following the headers
Elegant, standards compliant and automatic (finding out the user's locale without user input in JS isn't the easiest thing to do), but may result in awkwardness when a site is only available in a single language, but strings queried from the ESI are localized. No portability concerns, as ESI already uses CORS headers, and `Accept-Language`/`Content-Language` are simple headers anyway.

#### Using a query parameter
Very dirty method, headers are a superior option in almost every way. However, query parameters may be easier to use for less experienced developers.

#### Including all language variants
Adds unnecessary complexity, waste of bandwidth, adding a new language would require modification to the API definition.

I'm definitely in support of using the headers, and wouldn't mind if a query parameter was added as an optional override.

**Comment by tankbusta** [comment]
I think `Accept-Language`/`Content-Language` is the way to go as it is the standard for localization. Having to set the language in the query parameter for every request can be cumbersome. Most HTTP libraries let you set a list of headers for the lifetime of the client.

**Comment by a-tal** [comment]
added a new kwarg to the endpoint and service wraps for this, `translated` (boolean, default False)

@gitAskur ESI will now send a `sys:language` attribute of a string from `["de", "en", "fr", "ja", "ru", "zh"]`

@tsuthers-ccpgames @aquarhead we'll have to apply this kwargs to routes where it makes sense, where we are already accepting a qsarg for language we'll have to version bump that route and drop the param.

**Comment by gitAskur** [comment]
Easy enough to do for the monolith actions ESI uses. 

Brings up a thought for the events we will eventually push out and how we should handle that. We could just not push out string data (other than dates) and expect people to request their string form through ESI which then localizes them (or hopefully have a local cache where that is possible), or we could just push out M many events for the M many languages we support, either on different topics or more probably just with their own sys:language attribute. There are probably better ideas out there.

Nothing acute, just throwing it out there because I'm sure I didn't get the best approach while thinking about it for a minute.

**Comment by polarina** [comment]
@gitAskur I can't recall cases where there is localized data that isn't static (that is, in neither BSD nor FSD). I think it would make sense to simply not push out localized string data in events. Applications can either query the needed static data via ESI and cache it, or refer to the SDE.

**Comment by gitAskur** [comment]
Preaching to the choir bro. 

If I had my way I wouldn't be sending out any static strings despite their language and just expect people to either cross the wire again to specific ESI endpoints for ID -> String translation, or build their own local cache through either ESI calls or hosting the various data dumps available locally. But that wasn't a popular opinion. Can't remember why right now but I stopped pushing for it.

So since we are providing strings in English, it makes sense to provide them in all languages. But then all developers have to be aware of that fact or I need to make it so that it is all implied and developers don't have to think about it.

Having written this I am a bit leaning towards trying to pick that battle again.

**Comment by gitAskur** [comment]
@a-tal Can we use "en-us" rather than "en" as we function on Simplified English rather than English (UK)?

**Comment by gitAskur** [comment]
It´s no problem if not, and I am assuming we wont right now. It would just conform with our localization module (which is very problematic and probably conforms to no sensible standards)

**Comment by gitAskur** [comment]
Submitted change 1099090

**Comment by aquarhead** [comment]
We've added support for several endpoints now, unfortunately Google refuses to consider `Accept-Language` header on their CDN which we use for caching now. (see #209)

Anyway, closing this now since we've been adding support for quite some time.
