### ISSUE TITLE
/v1/corporations/{corporation_id}/contracts/ Cache timer is 4x as long as XML API

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#595]
/v1/corporations/{corporation_id}/contracts/ Cache timer is 4x as long as XML API

Request that the cache timer be lowered to the same cache time as the XML API; or lower, with include_completed=false?

**Comment by aquarhead** [comment]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_contracts.html

I'm not sure what 4x longer cache timer you're talking about, nor what does `include_completed` mean for this endpoint.

**Comment by lukasni** [comment]
The cache timer as mentioned in the docs does not correspond to what is actually in use in the XML API, where the timer seems to be about 14 minutes.

`include_completed` would be referring to the contract status, in most cases people will be interested in pulling only unfilled contracts. Having a parameter to only pull those which defaults to false would keep the typical response size down.

**Comment by LiamBoothby** [comment]
I join this conversation quite late, but since on slack it was asket for typical use cases I wanted to make sure to write the answer down.

We in Red Frog rely heavily on the contract API and our pilots use exclusevly our internal tool to select contracts, this way we can guarantee all our guidelines are followed and protect both our customers and pilots by mistakes and scams.

An API update of around 15 minutes (like it is with XML) allow us to offer to our customers an optional faster (and more costly) service giving in those cases max priority, clearly as fast the API update the sooner our pilots can see those contracts.

![red frog rush](https://user-images.githubusercontent.com/32896563/31710820-77cd1e68-b3f6-11e7-8730-66ea2f8836a2.png)

We had also the intention to implement additional tools like freighter tracking triggered by the contract acceptance, clearly with a cache of 60 minutes all this would be more difficult and we would have to find less optimal workaround or worse, drop some service entirely.

**Comment by rohimma** [comment]
Not sure where the 60 min ESI cache comes from, but if you take a look it says 5 min:  https://esi.tech.ccp.is/latest/#!/Contacts/get_corporations_corporation_id_contacts  

![image](https://user-images.githubusercontent.com/2255417/31711498-9faf9eb8-b3f8-11e7-809c-2489627a6d93.png)

**Comment by LiamBoothby** [comment]
@rohimma
You are looking at "contacts", not "contRacts" ;)

**Comment by rohimma** [comment]
Oh.. my bad..  
Cache timer is indeed 60 min.  

15 min (or shorter) Cache timer would be nice for the use case above. :+1:

**Comment by Conjur0** [comment]
As for an actual use case (from the OP); I'm in the same boat as @LiamBoothby 

I run a small courier/buyback group; and have had a services website running for about a year now, using The XML API's corp contracts. Without a reasonable cache time, this sort of capability begins to loose purpose.

I have almost entirely switched over to ESI calls; just waiting on a sane cache timer, to dump the XML API corp contracts :)

Courier side:
![image](https://user-images.githubusercontent.com/20806631/31725940-95f6214e-b3f3-11e7-9e3b-0d8603859f7b.png)

Buyback side:
![image](https://user-images.githubusercontent.com/20806631/31726282-83a2eb16-b3f4-11e7-8fdf-b004b090581d.png)
(* Some names have been blocked out to protect the guilty)

**Comment by alexoulapour** [comment]
Same issue as others above for us, PushX the hauling corp. We are a large hauling corporation second only to Red Frog. 

We run hundreds of contracts a week (500 - 900) and our customers rely on our customer service to have a pleasant experience with us. A timer of 1 hour would severely limit the abilities of our haulers and the satisfaction we can offer our customers. 

Customers often ask us if they have setup a contract correctly and they also use our customer website (https://my.pushx.net) to view their own contracts with our service. Having to wait an hour will cause issues as within that 1 hour we can have dozens of contracts submitted with customers waiting for an answer. This will also hurt our Rush services for delivery as we will not be able to detect them and service them quickly.

Please bring the cache limit at least to parity with the XML API of 15 minutes, or even faster.

Thank you

**Comment by ccp-zoetrope** [comment]
This has been released now and the existing v1 endpoint's cache timer has been dropped to 5 minutes (as well as being paginated using x-pages now). https://esi.tech.ccp.is/ui/#/Contracts/get_corporations_corporation_id_contracts
