### ISSUE TITLE
universe/names 404'ing on type ids.

### ISSUE THREAD

**Issue by mylesgallagher** [ccpgames/esi-issues#600]
# universe/names not resolving type ids

# Bug
universe/names is not resolving type Ids, always sending 404's.  Not sure to what extent, but it seems most type ids if not all type ids are not resolving.

### Request
/universe/names

for example:
`curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[34,35]' 'https://esi.tech.ccp.is/latest/universe/names/?datasource=tranquility'`

which should return tritanium and pyerite.

### Response
`{
  "error": "Ensure all IDs are valid before resolving."
}`
404

### Expected
Should be returning type name information, as none of the types are invalid.

**Comment by aquarhead** [comment]
I know what is going on, but unfortunately this is not a easy fix, so expect at least next week.

**Comment by gitAskur** [comment]
Will do a quick fix and try and get that out in tomorrows deployment. The real fix here is not mixing together item names, which are names of unique items in the game, and types, which are unique within the concept of types but since types are metadata of items then typeIDs and itemIDs can very easily have the same values.

The actual fix will have to be splitting these two things apart, at least on the monolith backend level.

**Comment by MoriNexia** [comment]
Although I don't know how your ID's are organised, wouldn't it be easier to add a parameter to specify which ID to search for be a little bit easier?

**Comment by gitAskur** [comment]
Does not matter as long as the IDs are all itemIDs. Well I could make a case for splitting them between; Owners, those itemIDs that are valid as the ownerID of another item; and locations those items which are valid locationIDs of other items.

But I don't think that's a distinction anybody except me would appreciate me making. I appreciate it because of a decade of working with this.. I do not think I should be applying my perspective to the perspective of an end user of ESI.

But typeIDs are not itemIDs in any way, they're just a further definition of an item, any given itemID must have an associated typeID. As such the disctintion between when you are asking for a typeName vs an itemName is clear. Hopefully... I've been living in this datamodel for a decade at this point so I might be assuming everyone has the same understanding as I do.

**Comment by gitAskur** [comment]
Fix should be rampaging around TQ by now.
