### ISSUE TITLE
Stations in the structure market pull

### ISSUE THREAD

**Issue by fuzzysteve** [ccpgames/esi-issues#615]
# Feature request

Augment the structure market endpoint to allow for pulling market data from stations. or add a station/system specific endpoint

### Route

/markets/structures/{structure_id}/

### Authentication

None for this

### Use case

I keep getting people asking why they can't request a station's market with this endpoint. being able to would cut down how many people ask me this.

**Comment by tsuthers-ccpgames** [comment]
We allow per-structure views not because we want to, but because the security paradigm on structures forces us to. The markets endpoint is by far the most heavily used endpoint and one of the most resource intensive.  Not providing a filter for stations allows us to get maximum cache hit percentage, which in turn lets us keep the cache time relatively low without performance problems. 

I appreciate it's a bit annoying to do this filtering client-side, but from a resource-usage perspective it's by far the most sensible way for us to handle the demand.
