### ISSUE TITLE
Clarify Contacts Labels on SSO Page

### ISSUE THREAD

**Issue by ddavaham** [ccpgames/esi-issues#632]
# Feature request

As of right now, if you were to auth with all three contacts endpoints, characters, corporations, and alliance, when the user lands on the SSO Authorization Page, all of the labels read read_contacts

[https://i.imgur.com/WqjIhpe.png](https://i.imgur.com/WqjIhpe.png)

### Route

/v1/characters/{character_id}/contacts/
/v1/corporations/{corporation_id}/contacts/
/v1/alliances/{alliance_id}/contacts/

### Authentication

Contacts

### Use case

End User clarification

**Comment by ddavaham** [comment]
SSO issue? Yes. Permission from Snowdin to post here? Acquired

https://i.imgur.com/0eP2bDF.png

**Comment by polarina** [comment]
The title is the scope name sans namespace and version. If the intent is for them to read `esi-alliance.read_contacts` that's on the SSO frontend's side of things.

**Comment by a-tal** [comment]
I really just want to change the description of the last one listed to "allows the reading of a corporation's contacts....." rather than "...a character's corporation's contacts..." to clarify that a bit.

but yes otherwise the display (or lack of) the namespace by the sso ui will need to be opened in sso-issues.

**Comment by tsuthers-ccpgames** [comment]
This is because the sso page does not display scope namespaces, and needs to be re-opened in the sso issues repo:

https://github.com/ccpgames/sso-issues
