### ISSUE TITLE
consistency: using full "type" names abbrevations

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#64]
not sure what the general opinion is on this but the alliance endpoint for example contains a field called 'executor_corp', this would preferably be named 'executor_corporation' (like in CREST), possibly even with '_id' at the end to signal that it has to be looked up.

another alternative would be to call the field 'executor' or 'executor_id' only since the alliance executor is always a corporation and i suspect the ceo field on a corporation wont be called 'ceo_char' (which would also fall under the main concern of this issue, 'ceo_id' or 'ceo_character_id' would be desirable imo)

**Comment by aquarhead** [comment]
I feel it's better to DRY. I also think this matters less because we have autogen clients and every "key" is documented (or should be).

So instead of using `timeDeclared` `timeFinished` `timeStarted` `timeRetracted` (in `/wars/{war_id}/`), I think just using `declared` `finished` `started` and `retracted` is enough. Because in the description we tell you this is a "Time that the war was declared" etc.. and its type(format) is `date-time`.

**Comment by Robbilie** [comment]
it would be time_declared […] no? :D 
i dont really understand how this is related to the issue i am pointing out, having _corp in the key seems a bit random

**Comment by aquarhead** [comment]
@Robbilie yeah, added some P.S. in my original comment :) just some side notes

**Comment by tsuthers-ccpgames** [comment]
So the convention for this is as follows:
1) No contractions. It should always be corporation, not corp.
2) The type of ID should always be explicit. It should always be corporation_id, never just id, even if it is inside a corporation object.

Endpoints that contravene these conventions should be bug reported

**Comment by Robbilie** [comment]
it should be name instead of (alliance|corporation|character)_name though…?
