### ISSUE TITLE
Add offline example for /status/ in docs

### ISSUE THREAD

**Issue by kriberg** [ccpgames/esi-issues#640]
# Feature request
Add the output from /status/ during downtime, in addition to the online example which is in the swagger docs now

### Route
/status/
### Authentication
N/A
### Use case
For those hard at work during downtime, it's difficult to get a sample of data showing what the reply will say during DT. Is it null, undefined, 'down' or? 
### Example returns
{
  start_time: null,
  players: 0,
  server_version: 31337
}

(This is a candidate for the world's most trivial bug report.)

**Comment by kriberg** [comment]
had logging going for every call the last 24 hours. Endpoint returns 502 during DT, which is perfect.

**Comment by a-tal** [comment]
yeah, you'll see 503's if ESI is informed of the downtime, 502's otherwise. All 5xx's share the Internal Server Error model (dictionary w/ a single key, "error").

/status/ will be similar to all other short-ish cache timed routes in this regard.

some routes with longer caching timers might have stale data to serve over downtime. others, like esi-routes, don't have a dependancy on the EVE server at all, so will continue to work as normal over downtime.
