### ISSUE TITLE
Freeport ID's can be pulled without auth, but you must be authed to pull its name.

### ISSUE THREAD

**Issue by NathenSample** [ccpgames/esi-issues#65]
While unauthed
GET /universe/structures/ 
returns a list of freeports, however trying to plug a freeport ID into 
GET /universe/structures/{structure_id}/
while still unauthed results in a forbidden

Seems counter intuitive, when the simple act of logging in allows me to resolve that information.

**Comment by tsuthers-ccpgames** [comment]
This is not a bug, but it's also something that can be changed, so converting to feature request.

This occurs because we are not special-casing the auth for public structures. Structure auth takes a character ID and a structure service type and tests to see if the user has access to the service. That test expects a character ID even if the structure is publicly dockable.

If we changed this, we would need a second endpoint for querying public structures, because AFAIK there is no way to represent an endpoint as "maybe needing auth" in the swagger spec.

**Comment by NathenSample** [comment]
Yeah talked with bartender regarding it, and while it seemed unintuitive at the time, discussion lead me to believe, and understand that the current behaviour is correct.

Ultimately I don't think it needs to be added, it was just an oddity at the time. I'll close this, feel free to leave it as such unless you have the urge, or scope, to reinclude the concept.

**Comment by deadlybulb** [comment]
My vote would be to either keep this open or open a new task (I'm happy to do the latter).  I think public info should always be pullable without auth.  Otherwise useful apps, for example dotlan, would be forced to implement an OAuth flow just to display the full gamut of public data.

I think you probably want a new endpoint for this.  However, you CAN create a swagger endpoint which allows a choice of auth scheme, and if you make one of those schemes basic auth where you either use well know creds or ignore the creds then you get the same effect as no auth.  Yes this is evil, but possible.  You're also on the hook for the ACL check but I guess you're doing that anyway.
