### ISSUE TITLE
Wallet Journal entires not consistent with xml api

### ISSUE THREAD

**Issue by kilgarth** [ccpgames/esi-issues#672]
An entry for a fee in ESI contains the refID, refType, date, amount, balance. There is no way to know who the fee was from, what it was for, etc... in the XML api, the ownerID1 and ownerID2 fields are populated with the relevant information.

There is a similar issue with contract related entries as well where the owner information is blank. However, for contracts, the contract ID at least is included as the arg, however requires a second call to get the contract information and then attempt to determine who should be owner1 and who is owner2.

**Comment by tsuthers-ccpgames** [comment]
There are quite a few enum entries suffixed "fee" in the wallet ref_type enum, could you give me a specific one that you see this on?

**Comment by kilgarth** [comment]
reprocessing_fee is one of them

**Comment by tsuthers-ccpgames** [comment]
Yep, verified. Not sure what's causing it yet.

**Comment by jennej** [comment]
I've just started pulling the journal entries and trying to work with them, but I've been running into this issue too. So if you need any more examples of places where data seems to be missing, I can try to provide more types where there are no party id's at all.

**Comment by tsuthers-ccpgames** [comment]
I'm pretty sure it's an underlying problem with the monolith action that will impact multiple ref_types, but the more specifics I can get the better!

**Comment by jennej** [comment]
Sorry, I got sidetracked by other stuff for a bit.  Here is a quick and dirty sql query of places where I'm getting NULLS.  

```
mysql> select distinct refType from corporation_wallet_journals where firstPartyId is NULL OR secondPartyId is NULL ;
+--------------------------------+
| refType                        |
+--------------------------------+
| contract_brokers_fee_corp      |
| contract_price                 |
| contract_price_payment_corp    |
| contract_reward_deposited_corp |
| contract_reward_refund         |
| copying                        |
| corporate_reward_payout        |
| manufacturing                  |
| market_escrow                  |
| market_transaction             |
| reprocessing_tax               |
+--------------------------------+

mysql> select distinct refType from character_wallet_journals where firstPartyId is NULL OR secondPartyId is NULL ;
+-----------------------------+
| refType                     |
+-----------------------------+
| contract_brokers_fee        |
| contract_deposit            |
| contract_deposit_refund     |
| contract_price              |
| contract_price_payment_corp |
| contract_reward_deposited   |
| contract_sales_tax          |
| copying                     |
| insurance                   |
| manufacturing               |
| market_escrow               |
| market_transaction          |
| researching_technology      |
+-----------------------------+

```

**Comment by galister** [comment]
Entries of ref type market_transaction are missing both parties. there is currently no endpoint to fetch a single transaction, so 3rd party devs would have to pull all of the transactions just to figure out where the parties of each entry.

Same deal with contracts, the contract-related entries do not include either parties, and you need to make a separate request to receive information about the contract. In-game, you can simply open up the wallet journal to see where the money went. Access to the wallet journal is adequate to see the parties. On ESI, however, you need the contracts role to obtain the party information about the wallet entry. This breaks parity, as a person who has the accountant role in-game, but not the contracts role, will be unable to read the wallet journal properly, they would be missing the party information, that is clearly visible on the in-game journal.

Parties should be the most basic element of any wallet journal entry and should not be omitted, even if the same data exists in the contract endpoint or transaction endpoint.

If the reason of this is that "the data exists somewhere else", then you might as well omit the date and amount fields, they are also present on the transaction / contract endpoint. They're still there, because they are basic information about entries and should always be there. 

The wallet endpoint should represent the wallet journal in-game, being quick overview. Give 3rd party devs the option if they want to pull the details about transactions and contracts, and not make them have to write switch-cases for ref types, then make thousands of senseless additional requests, just to restore the missing information, which could very easily be included in the original response.

**Comment by ccp-zoetrope** [comment]
v4 of character wallet journals has been [released](https://esi.tech.ccp.is/ui/?version=dev#/Wallet/get_characters_character_id_wallet_journal) and v3 of corporation wallet journals has been [released](https://esi.tech.ccp.is/ui/?version=dev#/Wallet/get_corporations_corporation_id_wallets_division_journal). They are currently labelled `dev` but will be promoted in 6 weeks.

The description you see in the client is now returned along with each journal transaction and more work has been put into figuring out what type "arg1" is. "arg1" from XML API is now called "context_id". 

Much more documentation about each attribute has also been added. These endpoints should not only be consistent with the XML API now but also more descriptive.

**Comment by galister** [comment]
The swagger spec states that context_id is of type int32, however there are ref types for which an int64 is returned.
