### ISSUE TITLE
alliance start_date for old alliance is missing

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#68]
on `GET /corporations/{corporation_id}/alliancehistory/` you'll receive an incorrect start_date (of  jan 1, 1970) for alliances started before sometime in 2008 in a corporation's alliance history.

a patch needs to be deployed to the monolith to resolve this. 

action: `get_corporation_employment_records-v1`

**Comment by gitAskur** [comment]
Some corporations are also still missing their create date as well. A few of them are player corporations so I'll go ahead and stamp the creating characters create date on that.

As for alliances, the lowest alliance create date time in the DB is 2004-11-24 13:03:00. I'll check the get_corporation_employment_records code and see if that's mangling up dates somehow.

**Comment by gitAskur** [comment]
SELECT MIN(recordID), MAX(recordID) FROM alliance.employmentRecords WHERE [startDate] IS NULL

Returns an interval that starts in the middle of the recordID range. So it's not all alliances created before a given time.. it's all alliances joined during a time interval where things were broken and were not fixed.

Guessing it was Unnar that both broke them, fixed them again and didn't fix up the data. This guy. This fucking guy.

**Comment by gitAskur** [comment]
This is great. There is one singular record on that range with a date!

That date has allianceID NULL and a timestamp of 2003-05-06 14:03:00 which is EVE's launch date when there were no alliances in this game.

**Comment by gitAskur** [comment]
All logs have been truncated so there´s no way of putting the data back there. Furthermore I'm seeing a pattern in the data where every consecutive clusterID range of these missing records cluster on the same allianceID which is clearly not a pattern generated by the game, but something I'd generate when doing a mass insert back into the table because something happened.

Possibly something like a lot of alliances suddenly lapsins for our mistakes; so maybe I can try and find previous records and use the timestamps there.

**Comment by gitAskur** [comment]
OKAY

These are indeed alliances that were created before the idea of alliance employment history was created and I probably just appended their employment records to the employment records table when that was discovered. So these records all happen before the records that preceed them but it's not possible to infer that from their position in the cluster because I am dumb.

So all these corporations are now considered founding members of EVE's first alliances and will thus have the start date of employment the same as the alliances create date. Because we do not have any general activity logs from 2004 and the alliance specific ones are the ones that we're missing data from.

**Comment by gitAskur** [comment]
EBS 7382 submitted into ESI branch. I´m not moving it anywhere until after tomorrows deployment.
