### ISSUE TITLE
/universe/ids does not return stations

### ISSUE THREAD

**Issue by Makeshift** [ccpgames/esi-issues#689]
# Bug

### Request
When sending an example list of items, such as `["Aakie Sekichi", "Goonswarm Federation", "Makeshift Storque", "48R-PS", "Karmafleet", "Tritanium", "The Forge", "N5Y-4N VII - Moon 20 - Guristas Logistic Support", "Jita IV - Moon 4 - Caldari Navy Assembly Plant", "Jita"]` to `/universe/ids`, it will not resolve station names.

### Response
```
{
  "agents": [
    {
      "id": 3018138,
      "name": "Aakie Sekichi"
    }
  ],
  "alliances": [
    {
      "id": 1354830081,
      "name": "Goonswarm Federation"
    }
  ],
  "characters": [
    {
      "id": 1206329897,
      "name": "Makeshift Storque"
    },
    {
      "id": 243070982,
      "name": "Tritanium"
    }
  ],
  "constellations": [
    {
      "id": 20000186,
      "name": "48R-PS"
    }
  ],
  "corporations": [
    {
      "id": 98370861,
      "name": "KarmaFleet"
    }
  ],
  "inventory_types": [
    {
      "id": 34,
      "name": "Tritanium"
    }
  ],
  "regions": [
    {
      "id": 10000002,
      "name": "The Forge"
    }
  ],
  "systems": [
    {
      "id": 30000142,
      "name": "Jita"
    }
  ]
}
```

### Expected
For the output to include the two stations in the request.

**Comment by ccp-zoetrope** [comment]
We have found since releasing this endpoint that any names that have a word followed by a space, followed by a "-", followed by a space will not return correctly. It seems those two station names use this convention and therefore are not being returned. We have identified the problem in our search backend but it will not be fixed until the beginning of January unfortunately.

**Comment by ccp-zoetrope** [comment]
This has been fixed and is working now.
