### ISSUE TITLE
esi-clones.read_attributes.v1

### ISSUE THREAD

**Issue by skiedude** [ccpgames/esi-issues#708]
https://esi.tech.ccp.is/ui/#/Skills/get_characters_character_id_attributes exists, however I am not seeing a match for esi-clones.read_attributes.v1 in the scopes list. 

Is this obtained using a different scope?

**Comment by ddavaham** [comment]
Please check the spec next time

![cnwok23](https://user-images.githubusercontent.com/7141998/34658512-ab25659e-f3fd-11e7-8426-4eddfb38b2b6.png)

**Comment by skiedude** [comment]
Thanks for the quick answer and help, where does one see the spec? I'm relatively new to all these swagger stuff

**Comment by ddavaham** [comment]
Alright, since you're new Ill give ya a break. Jk just giving you a hard time.

The https://esi.tech.ccp.is/ui/ site is generate from a large json file that you can view by going to https://esi.tech.ccp.is/latest/swagger.json. 

So to expand on this further, as you look around the site, you will see the main route /latest/, the dev route /dev/, the legacy route, /legacy, and then the versioned route /vX, where X equals the latest stable version of that endpoint.

We highly recommend that you use the a versioned routes, so /vX instead of /latest. Why? because if an update to that endpoint get pushed out that changes the structure of the response and your application is using /latest/ then it will break your app, however if you using a versioned route then you will continue to get the same response until you can go in and update you code base to handle the new response structure. I said all of that to say this.

If you view this [json file](https://esi.tech.ccp.is/_latest/swagger.json), the routes listed in the paths property are prepended with the latest stable version number. 

Hope this all helps.

**Comment by skiedude** [comment]
Great info, many thanks
