### ISSUE TITLE
/characters/affiliation/ not at parity

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#719]
# Inconsistency

### Routes
/characters/affiliation/

vs 

https://api.eveonline.com/eve/CharacterAffiliation.xml.aspx

### Description
/characters/affiliation/ Allows one to supply up to 1000 character IDs and gets back the corporation and alliance. If any of the IDs are not character IDs however you get just an error

However the api.eveonline.com/eve/CharacterAffiliation.xml.aspx endpoint allowed alliance, corporation, or character IDs. It also returned the faction that the alliance, corp, or character was affiliated with.

Considering many of the current endpoints only return a client_id against the target in question and not whether the target is a character, corporation, or alliance it makes actually evaluating their friendliness difficult. Under almost all of the XML endpoints you got an ID and Name and getting friendliness was just a matter of getting all the IDs and hitting the Character Affiliation Endpoint.

Under ESI for instance if I want to get a list of all transactions and how friendly the ids are I must gather all the IDs

Then I must submit all the ids to /universe/names/ and seperate the alliances, and corporations from characters

Then all characters get submitted to /characters/affiliation/ to get everything but faction
I must then somehow get faction information

Then all corporations have to get their information 1 by 1 at /corporations/{corporation_id}/

Then all alliances  1 by 1 at /alliances/{alliance_id}/

Since I am using this for jackknife and also have a highlight features I need to repeat this process with the highlight list

If I assume the worst case on /characters/{character_id}/wallet/transactions/ and 2500 transactions returned and all corporations and alliances instead of characters
I would need to make 11 XML calls (1 call to transactions and 10 calls to https://api.eveonline.com/eve/CharacterAffiliation.xml.aspx at 250 max each)
or 2504 ESI calls(1 transaction call 3 /universe/names/ to find what they are and 2500 alliance or corp calls)
for the same information

This seems a little excessive
### Resolution
Add corporations and alliances to the accepted entities and add faction information

**Comment by ccp-zoetrope** [comment]
As far as I can tell there are two questions encapsulated in this.

1.
Q: How do I get faction info for a character using /characters/affiliations
A: If you look at the model of the JSON returned here: https://esi.tech.ccp.is/latest/#!/Character/post_characters_affiliation which looks like this:
```
post_characters_affiliation_200_ok {
character_id (integer): The character's ID ,
corporation_id (integer): The character's corporation ID ,
alliance_id (integer, optional): The character's alliance ID, if their corporation is in an alliance ,
faction_id (integer, optional): The character's faction ID, if their corporation is in a faction
}
```
faction_id is optional and will only be returned if the character is enlisted in faction warfare. So you can expect to get the faction_id if a character is enlisted in faction warfare. If you find any case where a character should have a faction but it does not show up then please file a separate bug report.   As an example here is a character that is part of faction warfare (who I got from https://esi.tech.ccp.is/ui/#/Faction_Warfare/get_fw_leaderboards_characters): 
```
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[241457623]' 'https://esi.tech.ccp.is/latest/characters/affiliation/?datasource=tranquility'
```
There is an issue with NPC characters not showing factions at the moment though: https://github.com/ccpgames/esi-issues/issues/732.

alliance_id is also optional so if a character is not part of an alliance then it will not show up as well (instead of being 0 like in the XML API).

2.
Q: Can you add corporations and alliances as part of /characters/affiliations?
A: No but you could make a feature request for corporations/affiliations and alliance/affiliations if you feel like you really need it. However, you can see all the corporations that are part of an alliance here: https://esi.tech.ccp.is/ui/#/Alliance/get_alliances_alliance_id_corporations and you can get all the info you need from other endpoints.

The XML API had a lot of redundant and duplicate information in all of its endpoints and ESI has been striving to not do the same thing. You will have to make more calls, which could be a lot in the case listed above. You should consider caching things like corporation info and alliance info locally to help ease the burden though.

**Comment by whinis** [comment]
I would make the feature request but honestly asking anyone who deals with the transaction API or wallet API to essentially cache all current corporations and alliances sounds extremely heavy handed. Especially whenever /characters/affiliations previously accepted all entities and now in ESI not only does not but errors. 

As it stands I would rather get away from adding more complexity to my applications such as a ram cache for information that used to be easily accessible.

**Comment by ccp-zoetrope** [comment]
Looking over your comment again, you could cut out quite a few calls with some in memory store. When you hit up /universe/names/ it will give you the names of each corporation/alliance/character, if you keep a pairing of ID -> name that can be referenced later, then you can avoid hitting up /alliances/{alliance_id}/ and /corporations/{corporation_id}/, since all the XML API character affiliations route did was give you names and IDs. 

As far as factions names you could keep a small enum of IDs -> names gathered from this endpoint: https://esi.tech.ccp.is/ui/#/Universe/get_universe_factions. 

Looking a bit deeper into https://api.eveonline.com/eve/CharacterAffiliation.xml.aspx, you could pass in alliance and corporation IDs, but it would never return correct info about their affiliations. I assume you were using this to find their names, which you can just replace with /universe/names/ now instead.

**Comment by ddavaham** [comment]
This is what I do. I have a single table called entities that store systems, stations, structures, characters, alliances, and corporation. Same as the universe name endpoint, well minus the structures, but you get the point. Any way, never have had to use the affiliations endpoint as everything it can do can pretty much be done with the uni names endpoint.

**Comment by whinis** [comment]
I was using the affiliation to mostly get a characters corp, alliance, and faction. a corps alliance and faction, and an alliances faction. I never needed to get the names as every xml endpoint already gave me that for the most part. If it returned incorrect information I never noticed, if you sent in a corp the character ID would be 0 but the corp ID and alliance ID would be correct, if you sent in an alliance corp and character were 0 but alliance id was correct (and faction if they were in one).

Getting names is not a massive problem due to the bulk name lookup but getting affiliations for anything not characters is just a massive pain currently. Since I am using this essentially for a spy checking tool (regardless of if you agree with it or not) getting up to date affiliations is rather important.
