### ISSUE TITLE
GET vs. POST in several APIs

### ISSUE THREAD

**Issue by tankbusta** [ccpgames/esi-issues#78]
Just curious why some APIs such as `/characters/names/`, `/alliances/names/` are GET's instead of POSTs? While POSTs should probably be reserved for a R/W operation; it feels kinda dirty submitting a potentially large list of character/alliance IDs in a GET request.

**Comment by wtfrank** [comment]
Its standard HTTP REST stuff. The answer is to do with whether the call to the method has consequences or side effects. See paragraphs 9.1.1 and 9.1.2 of https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by tsuthers-ccpgames** [comment]
So the background is that in some other endpoints where a user might want to submit a really big set of data we are doing POSTs for what should arguably semantically be a GET. /characters/{character_id}/cspa/ is a good example of this.

We do it because various different tools have various different maximum URL lengths, and we envisage scenarios where people might want to submit much longer queries than that.

It's a bit of a compromise though. Apart from being pretty unRESTful, we also currently don't have the tooling to expose the cache that's present on these "POST" endpoints. Because they're for retrieving information and not writing it, they do actually have cache timers behind the scenes, but we can't tell anyone that through the swagger spec, which I don't like.

I'm open to convincing arguments either way!

**Comment by HakShak** [comment]
This biggest different between these types of endpoints is state. :/

We struggled with this a bit since for example CSPA calculations will always be stateful and on top of that will probably have a huge list of IDs to deal with. It's not RESTful because it's not stateless.

However, with /*/names/ you can get away with missing out on part of the information if a router somewhere decides that your URL is too long. These names are stateless. It's what they are.

It's not 100%, but it was a compromise to move forward.

**Comment by ccpStuart** [comment]
See above statement, compromise remains.

**Comment by Robbilie** [comment]
as long as the /universe/names/ endpoint stays post im happy :D
