### ISSUE TITLE
return 503 when server is starting

### ISSUE THREAD

**Issue by guiguilechat** [ccpgames/esi-issues#797]
At the moment, esi returns 502 "bad gateway" on downtime.

Make it return 503 "Service Unavailable" instead.

**Comment by SpeedProg** [comment]
But ESI is up just the gateway is down

**Comment by guiguilechat** [comment]
https://tools.ietf.org/html/rfc7231#section-6.6.4

This allows to add a retry-after header that specifies when the server is supposed to be ready.
 - if server is starting, send the ETA + random 0-60 s (to avoid user spikes)
 - if server is not starting, send minimum server start + 60s.

Hence an application that should call ESI based on time would simply make its calls wait.

**Comment by Aidansavage** [comment]
IIRC, if ESI is notified of downtime, it returns 503. If it's NOT aware of downtime occuring, it returns 502.

Additionally, if you know when downtime occurs (you should, it rarely changes day to day) it's not hard to automatically back off requests. Further, it's also possible to still get valid results from ESI if you're poking endpoints who's cache lifetime is still active.

**Comment by a-tal** [comment]
@Aidansavage is correct

@guiguilechat ESI is only told when the server is up, not when it begins starting up. Also it might not always be told about a server shutdown, depending how that shutdown happens.

generally though: a 502 means ESI tried to talk to the datasource backend, but the response timed out. A 503 means no attempt was made because ESI knows the datasource is down atm.
