### ISSUE TITLE
Chat channel APIs not functioning?

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#810]
# Bug

### Request
https://esi.tech.ccp.is/latest/characters/ *characterID* /chat_channels/
Where *characterID* is the one for which an authorisation token is supplied, scoped for `esi-characters.read_chat_channels.v1`.

### Response
502  
Error: Bad Gateway  
`{
  "error": "No reply within 10 seconds"
}`
### Expected
200  
*A list of chat channels*

I've tried it for several characters via https://esi.tech.ccp.is/ui/ so it shouldn't be a case of using one with a lot of channels.

As as aside, the XML API for chat channel seems to have been broken as of the 20th March update, and we need the ESI one working to replace it asap. Vital for NPSI communities.

**Comment by Robbilie** [comment]
maybe, just maybe, this is related to the new chat system ^^

**Comment by DaneelTrevize** [comment]
But being as no one seems to have reported it previously, I was wondering if it's something that just got broken this DT today, rather than since deployment.  
Also p much impossible to build a fix to the XML one going down unannounced without the ESI one working.

**Comment by Robbilie** [comment]
its alright that you reported it, the reason for it being down is quite obvvious though :D

**Comment by tsuthers-ccpgames** [comment]
RE the original ticket:

That error is usually given during downtime, and it means you're request couldn't reach the monolith at all. We've had quite a few unscheduled DT's in the last few days and this ticket was filed directly after daily downtime today, any chance it was just downtime when you tried?

Let me know if it's still doing it now, while the server is up?

More generally RE the channel endpoints:

At the moment I would expect this endpoint to return data, but that data will get increasingly stale because it's not being updated at the moment. Unsurprisingly this is fallout from the new chat system. We're going to wait until the chat system has stabilised and then review all chat-related endpoints completely, since the new chat system might imply new models for the data behind them, and various pieces of plumbing need to be connected in different places behind the scenes.

For any that do require new models, it's likely that we'll do something similar to the structure vulnerability endpoints where we convert endpoints with outdated models to return empty/meaningless responses and give everyone a reasonable timeline to move to the new ones. But probably that won't be happening for a week or two, because API access to chat is very low priority in comparison to the in game experience, and that's what the chat team is currently focusing on.

**Comment by DaneelTrevize** [comment]
Yes it seems it's working atm, though an immediate concern is the size of the response, or rather lack of ability to specify a single/set of channel IDs to limit it to (reasonable to raise as a feature request?).  
Ideally users would be able to limit API access to specific channels, but that'd probably be a significant feature request and not obvious where the mapping for that would be managed.

As for impact of chat channel changes/bugs, SpectreFleet alone maintains just shy of 100,000 unique sessions per month visiting the website in order to see the MOTD schedule out of game. Previous-CSM Jayne Fillon said it's a ~13k players community, and while it may be the largest NPSI one atm, it's certainly not the only, and all are impacted by broken chat channels (because they use them to substitute in-game corp mechanisms).  
I hear that in-game there's problems with make any significant changes to channel operator & banned lists, which would kill this NPSI community's ability to manage their own FC hierarchy & kick bad apple players.

Our holy grail has always been the ability to write the MOTD & other channel attributes via an API, then we can drive updates via our site where we can use a far more robust editor than Eve provides (as well as auto-sync permissions for several related channels). Again as per https://spectrefleet.com/motd_format, CCP's "fixes" to the in-game MOTD editor in June 2017 did not fix the issues around character limit, character counting and/or accurate display of the true current MOTD without leaving & re-entering a channel/restarting your Eve client. Try it, the limit is simultaneously 3000, 4000 and 4222 according to Eve.

**Comment by DaneelTrevize** [comment]
Can this get the label:esi-channels, partially so we know that's still in use and #349 won't be missed in any upcoming chat channel rewriting?

**Comment by ccp-zoetrope** [comment]
@DaneelTrevize so this issue actually should be closed because it was about the 502, which was determined to be because of downtime. However, you say you don't want this issue to be missed with upcoming chat channel rewriting. I would prefer a new issue is made with the details you specifically think are relevant in the conversation on this issue.

I'm assuming the part you want to not be missed in future chat channel ESI rewrites is:
>  it'd be very useful to be able to read who made the latest change to the attributes

But I'm not entirely sure 😄

**Comment by DaneelTrevize** [comment]
Done, #817

**Comment by DaneelTrevize** [comment]
Any sort of ETA for /characters/{characterID}/chat_channels/ returning data that isn't 2 weeks old with a claimed expiry of 5minutes in the future?

**Comment by erlendur-ccp** [comment]
See https://jira.ccpgames.com/browse/TQ-129169.

**Comment by DaneelTrevize** [comment]
Not sure if that was intended for me, as unsurprisingly "you are not authenticated to access CCP Games JIRA or Confluence", and I don't think I'd get a positive response to the suggested email solution.

**Comment by ccp-zoetrope** [comment]
No it was intended for CCPers as a reference to our internal issue following this same issue.
