### ISSUE TITLE
SDE release status through ESI

### ISSUE THREAD

**Issue by jameson2011** [ccpgames/esi-issues#814]
# Feature request

I'd like to ask for a new ESI GET endpoint that gives current SDE export file status. 
The endpoint would serve as a hook for both automated CI/CD pipelines to kick off converter jobs and general developer QOL.  The endpoint would return:
* URI of the current SDE ZIP file
* MD5 hash of the zip file
* UTC date & time of the release
* The minimum applicable Eve client version number. Distinct from the ESI API version number, Eve clients' versions will up-tick between releases, whereas SDE release versions would not necessarily keep up. EDIT: minimum server version, from https://esi.tech.ccp.is/latest/status/, should suffice (and a lot easier to locally verify)

Cache expiry & other response headers: at your discretion.

### Route
At your discretion. Alongside ESI's metadata perhaps?

### Authentication
No need that I can think of.

### Use case

* CI pipelines periodically poll this endpoint. On a new version detected, the newly exported archive is downloaded, transformed, and pushed to 3rd party publications,

* Tweetfleet slack bot: !esi sde and so reduce clutter.

* Self-updating 3rd party tools 

This is a pure QoL request. It helps simplify client code, where clients have a mix of ESI & HTML scraping. 

### Example returns

Payload:
{
 "uri": "https://cdn1.eveonline.com/data/sde/tranquility/sde-20180214-TRANQUILITY.zip",
  "released": "2018-02-18T00:00:00Z",
  "eveVersion": "xxx",
  "md5": "134134432" 
}

### Previous XML or CREST route
N/A

Cheers!
- J

**Comment by guiguilechat** [comment]
what about 
```java
	org.jsoup.nodes.Document page = Jsoup.connect("https://developers.eveonline.com/resource/resources").get();
	Elements a = page.select("a[href*=data/sde]");
	return a.attr("href");
```
That is what I use to get the last version of SDE.

**Comment by jameson2011** [comment]
HTML scraping is fine as a stop gap, but just not viable medium-long term. Small markup changes break integrations, etc. etc.

**Comment by tsuthers-ccpgames** [comment]
The SDE has nothing to do with ESI, it doesn't make sense to link the two of them together. There's been some discussion about adding an MD5 sum somewhere on the resources website to allow people to quickly poll to see if the contents has changed.

Most people don't have the previous SDE on hand to compare the MD5 though, they use a third party conversion, so in my opinion it's kind of marginal to add an MD5 sum over just watching the filename since you'd have to fetch and store the previous one to compare anyway. If anyone would like to convince me otherwise I'm open to it, but this is conversation for #devfleet, not an ESI issue, so I'm gonna close this ticket :)
