### ISSUE TITLE
Endpoint for market orders WITH citadels included

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#826]
# Feature request

### Route

Either use existing /markets/{region_id}/orders/ with some flag, or make a similar one.

### Authentication

Obviously required, with probably a new scope, since you can infer the structures available.

### Use case

Right now there's no direct way to get an order list which matches the same thing the player sees in Eve. We can only get public orders or orders per citadel, which given the fact there's no endpoint to fetch available citadels, requires querying **all** citadels in given region. This results in a ton of requests with a ton of errors, if access data is not known upfront. Also, it depends on having the citadel list upfront, which again, is not available from ESI.

### Example returns

Same as /markets/{region_id}/orders/.

**Comment by tsuthers-ccpgames** [comment]
This was alluded to in my comment here: https://github.com/ccpgames/esi-issues/issues/615

But that perhaps lacks clarity and is also talking about the issue from the other direction, so here's the concrete version.

The market endpoints are the most resource intensive endpoints in the API, by something like a full order of magnitude. A complete Forge market pull is usually in the order of 77 megabytes of data.

To integrate citadel market orders into this, we'd have to integrate a citadel auth check for every citadel in the region, which is crazy expensive in and of itself, and then present a different view per character, which would force us to move the cache in one layer and live assemble the data from a mix of cached and uncached data on a per person basis.

We could maybe do that, but we could not do that and also have a 300 second cache on that endpoint. If we assembled the views for you, it would have to be behind something like a 1 hour cache, otherwise the whole process is too expensive to do for every character that makes a request, particularly since lots of people will be doing the same request with multiple slightly different characters to try to get as complete an overview as possible.

By splitting the data into views that are shared between multiple people (the entire public market, and then per structure because one structure is the minimum granularity of difference between two players), we can ensure that we're a) not priming data no one cares about and b) getting as high a cache hit as possible, which lets us keep the cache expiry time low.

So although from a UX perspective I understand and sympathise with the request, unfortunately from a technical perspective it's a clear no-go, sorry :(

**Comment by krojew** [comment]
That's unfortunate, given we have no means to actually see the same thing the Eve client sees. If making an "available citadels" endpoint is more probable, that would also help much. Right now, the whole process you described is being pushed down the ESI clients, which is a real pain for the end users (and I imagine nobody on both sides likes handling a crapton of 400s).

**Comment by Behelith666** [comment]
If the structure ID's are included in the buy orders the application devs will have to pass a request in the /universe/structures/{structure_id}/ which is resource intensive as it requires an auth. Otherwise the list of orders will have missing data. So then it's better for application quality and resource optimization not to include the structure ID's.
