### ISSUE TITLE
What is the difference StructureServicesOffline & StructureWentLowPower 

### ISSUE THREAD

**Issue by Fundaris** [ccpgames/esi-issues#831]
Hi,

I just wanted to know what is the difference between these two. Because when StructureServicesOffline happens the structure will go into StructureWentLowPower. 
/v2/characters/{character_id}/notifications/

**Comment by MiSwit13** [comment]
My guess would be if you had multiple services, then the StructureServicesOffline  would tell you if 1 or more of them went offline while StructureWentLowPower would occur when all services were offline and the structure itself went into a low power state. I don't know that for sure, but that's how I interpret those notifications.

**Comment by ccp-zoetrope** [comment]
StructureServicesOffline triggers when a structure tries to consume fuel for a service module but doesn't have enough. So it won't trigger if the service modules have been manually offlined and doesn't necessarily mean that all the service modules have gone offline (the structure might have had enough fuel for some but not all services). StructureWentLowPower triggers when the structure enters low power mode whether it's because of low fuel or manual disabling of service modules.
