### ISSUE TITLE
Refill ESI after every PW change .. seriously?

### ISSUE THREAD

**Issue by Valkorsia** [ccpgames/esi-issues#836]
### Request

OK, as a CEO, I have better things to do than chase around 278 people who have changed passwords on ESI their Eve accounts .. It requires them to re-add ESI keys .... they lose services (Mumble, Discord, Jabber, forums) in our IT structure if they change an account pw .. and don't change (refill out) the ESI key, too .. its totally retarded ... XML keys never required this ... please, for the love of God, change this ..

o/

Valk
CEO/SPVG
http://evemaps.dotlan.net/corp/Spartan_Vanguard

**Comment by antihax** [comment]
Build a system to deal with it and mail them when they invalidate. 

Also this is an SSO issue, not ESI.

**Comment by ddavaham** [comment]
Have to agree with this. You need to post this in https://github.com/ccpgames/sso-issues/issues

**Comment by Aidansavage** [comment]
Additionally, XML/CREST not doing that is _precisely_ why ESI does. Not to mention it's a lot less obvious where to remove ESI authorizations, especially since some people are less than descriptive in naming the applications in question (who the heck names it "TS Identity Manager v2"?). And no easier way to remove authorizations in bulk. Compensate with what antihax suggested.

And yea, SSO issue, not ESI.

**Comment by Valkorsia** [comment]
OK, will file there .. Thanks, gents.

**Comment by a-tal** [comment]
thanks all
