### ISSUE TITLE
/v1/universe/asteroid_belts/{asteroid_belt_id}/ inconsistent doesn't return own id

### ISSUE THREAD

**Issue by HakShak** [ccpgames/esi-issues#869]
# Inconsistency

### Routes
/v1/universe/asteroid_belts/{asteroid_belt_id}/
### Description
All other universe routes return their own id. Most likely because #813 is newer.
### Resolution
Add asteroid_belt_id to result

**Comment by HakShak** [comment]
P.S.: Read this as if it were a third party request as I don't know if this was intentional and I am still on "vacation" 😜

**Comment by Robbilie** [comment]
I once requested the IDs to be added to the body and I was told it was redundant to the id in the url. But if you want that too I'll happily take an id in the body chimi :P

**Comment by a-tal** [comment]
this was intentional. it's actually the universe endpoints that are inconsistent with the rest of ESI.

typically we don't echo attributes of the request when it can be avoided (ie; any non-bulk endpoint). this endpoint was created in that spirit, so that we don't have to version bump it when we get around to making the rest of the universe endpoints consistent with ESI.
