### ISSUE TITLE
Market orders paginator

### ISSUE THREAD

**Issue by georgwacker** [ccpgames/esi-issues#90]
Currently there is no way to tell how many pages /markets/region_id/orders/ will return, in CREST we had the next attribute to iterate over all the pages. 

Is it per design that one shall iterate blindly until 422 occurs?

I would prefer the old method with an href to the next page, or perhaps a flag that the current page isn't the last one.

**Comment by Kyria** [comment]
I don't believe this is really useful : as long as you know "how to stop" looking for new pages, it's fine. 
With adding this info somewhere in the response, the backend will have to calculate the number of elements, then the number of page, when almost all regions but a few will have 1 or 2 pages at most. 

The only thing you have to do atm is to increment the page number until you have an empty list as a response from ESI.

**Comment by jamesremuscat** [comment]
The flip side of that argument is that you're guaranteeing at least one more HTTP request to ESI than is needed. It also makes it harder to parallelize requests.

**Comment by evrial** [comment]
Blind pagination is a bad practice, first of all it's sequential operation, second - API could return 5XX error or timeout while your JS app freeze in callback and you can't handle without complete data.

**Comment by DianaOlympos** [comment]
Main advantage of knowing the number of pages : you can query all of them in parallel.

**Comment by polarina** [comment]
> Main advantage of knowing the number of pages : you can query all of them in parallel.

If the most common, if not the only, operation on the market endpoints is to fetch all pages at all times, pagination is of not much use and should simply be removed.

**Comment by DianaOlympos** [comment]
Well outside of that, the only other use would be to search for a particular order... and i guess that is all...

**Comment by aquarhead** [comment]
Is using the `Link` header (https://developer.github.com/guides/traversing-with-pagination/) a common practice? (it's an RFC https://tools.ietf.org/html/rfc5988)

**Comment by evrial** [comment]
```curl -I -X GET --header 'Accept: application/json' 'https://esi.tech.ccp.is/latest/markets/10000002/orders/?order_type=all&page=1&datasource=tranquility'
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Nov 2016 13:21:52 GMT
Content-Type: application/json
Content-Length: 7188776```
100mb estimated response body if pagination removed.

**Comment by polarina** [comment]
> 100mb estimated response body if pagination removed.

How much is the response size with gzip compression? You can pass the `Accept-Encoding: gzip` HTTP header and get the response compressed.

**Comment by Kyria** [comment]
The Content-Length is not available with gzip compression, but it's around 700-800ko per page

**Comment by evrial** [comment]
Right, 500kb.

**Comment by Regner** [comment]
@aquarhead no, using the Link header is not common at all, at least not from my experience.

**Comment by rottjr** [comment]
So as I understand it we need to be making requests expected to have multiple pages of data with the <code>Accept-Encoding: gzip </code> and need to iterate through until we receive an empty list? This seems like anew inherent flaw, would it not beven just as efficient to provide a list of endpoints for each list? This would allow you to run all queries in parallel and even in async as well as allow you to pick and chose your pages if you would like. Seems you would be doing the same amount of queries except you wouldn't be making a query for blank info and you would be able to traverse or mass pull the data very easily.

**Comment by georgwacker** [comment]
@rottjr How you would process the data should be decoupled from the actual API, though. You can just as easily process a subset of the entire list locally, or spawn threads that process the data. 

My suggestion would be to force the gzip encoding and transfer the entire list. Having the option to chose a page for actual data analysis is not applicable, because you have no influence on the slice and how it is grouped/sorted.

One concern however, might be that you are forced to handle the entire list which might lead to some memory management.

**Comment by rottjr** [comment]
@georgwacker I may have missed a facet of this. A solution for not knowing the slicing/sorting would be to create a param for page size. IE: lines=x or maxLines=x

The reason I say this is because I agree that pulling all information would lead to a potential memory leak, especially if you're looking at a large number of users.

Just an idea.

**Comment by zweizeichen** [comment]
This would still not solve the problem of the cache updating while iterating over the pages. At the moment you cannot be sure that the data you're getting from each page is consistent with the others.  Either avoiding pagination entirely (maybe generate market dumps at fixed intervals for each region and cache them in gzipped format in a K/V store in the backend) or adding a header when the underlying data was fetched would be a solution for that problem. Gzipping a JSON data structure this size within the request/response cycle would probably not be a good idea.
A dirty workaround for minimizing the risk of fetching inconsistent pages is launching several concurrent requests at once (more than there are pages) and let the "overfetched" requests die. This is not a nice situation for both sides.

**Comment by cjslep** [comment]
I was surprised to find this pagination limitation as well. I agree with @zweizeichen for regional orders: take a snapshot and gzip offline. One gzipping is done, serve it in as a cached value. I don't know how the market database is indexed but since orders probably have a created/modified timestamp, a different endpoint can return only the orders that were modified/created/removed since the gzipped snapshot was taken, meaning clients can fetch large older orders in bulk from the cache and then aggressively query a smaller list of orders that have changed.

It would be a lot of work, and only really worth the effort if the caching system itself is a big issue OR if it is a big issue to query an empty page. From a client's perspective it's cheap to overfetch, but as a good steward it would be prudent to not DoS the marketplace API.

**Comment by a-tal** [comment]
After reading the comments here and looking at various RFCs, I've decided they all suck and we should go the route of adding a `X-Pages` header.

I don't like `Link` headers because I don't want to recreate urls w/ parameters there, and there's a slippery slope of supporting not just rel=last, but also first, next, previous... which would be a whole pile of useless junk in 99% of use cases.

if you hate the idea of `X-Pages` now's the time to speak up.

otherwise the flow generally would be: 

- request some paginated endpoint
- check if the `X-pages` response header is more than 1
- spin up `X-pages` - 1 threads to get remainder

**Comment by a-tal** [comment]
`X-Pages` is live on market region orders.

part of the `paginated` kwarg to the `@esi.endpoint` and `@esi.service` wraps.

@gitAskur @aquarhead @tsuthers-ccpgames for future reference, any `sys:pages` return in data_relay attributes is used as the `X-Pages` response header. just make sure to remember to mark the endpoint as paginated so the documentation is added for you.

**Comment by aquarhead** [comment]
This will be deployed on 27th
