### ISSUE TITLE
Return `Data about a structure` if character has assets inside of it.

### ISSUE THREAD

**Issue by herpaderpaldent** [ccpgames/esi-issues#916]
# Bug

https://esi.evetech.net/ui/#/Universe/get_universe_structures_structure_id
Delivers only the structures name when you are on the ACL. This is inconsistent with ingame Mechanics.

## Request

`GET /universe/structures/{structure_id}/`

## Expected

Do return structure details, if character has assets in structure.

**Comment by wvdvegt** [comment]
Some of the structures are planetary custom offices in my data. 
But that still leaves me with a number of unaccounted location id's I can't resolve.

**Comment by MrBMT** [comment]
To add to this, when you make a call to a structure you no longer have permission to retrieve the ACL for, it returns a 401 error.

This 401 counts against your ESI error limit, and reduces it by 1 each time.

So, when you're querying structures based on where characters have assets, if you have a number of characters with assets in citadels they no longer have access to, you can quickly exceed the ESI error limit, and no longer be able to perform ESI calls.

**Comment by skyride** [comment]
Here's the no 1 scenario I encounter on an infuriating regular basis with this.

- Character has assets in a structure they can no longer dock in for any number of reasons
- My application pulls the assets of that character
- location id is said structure
- my application has never seen this structure before and attempts to resolve it
- is unable to do so due to no docking access
- I now have a detailed list of assets with consent from the owner without any way to find out where they are in space

Meanwhile ingame this information is perfectly accessible through the personal assets window.

The real issue as far as game design is concerned as I understand it is using the structures endpoint to scan for new/anchoring structures. As long as the [universe_get_structures](https://esi.evetech.net/ui/#/Universe/get_universe_structures) endpoint continues to work the same I'm not sure this is an issue.

Additionally this creates issues for many applications by unavoidably contributing to their error rate limit allowance.

**Comment by herpaderpaldent** [comment]
i made a litte example of the issue: 
![image](https://user-images.githubusercontent.com/6583519/39962434-8a83f996-564e-11e8-8394-1f02687cea3a.png)

**Comment by ddavaham** [comment]
This is not an issue. This is functioning as designed. Game Design does not want us to have access to the names of structures that the character is not on the ACL for. It is just that plain and simple. You, the developer, regardless of whether or not the owner of the assets has given you permission to the view the assets, does not have access to the structure any more and therefore cannot resolve the name of the structure. This is very simple logic. Please stop posting issues about this and use the search bar to see previous issues about this topic.

An explanation of the reasoning behind this
https://github.com/ccpgames/esi-issues/issues/674

A work around for working with assets
https://github.com/ccpgames/esi-issues/issues/643

Another explanation of the reasoning behind this decision by a fellow Third Party Dev
https://github.com/ccpgames/esi-issues/issues/510

**Comment by warlof** [comment]
According to the report amount you have, assume it definitely need a revamp! 

This is actually a no match with in game comportment.

And, we actually are stuck in an infinite throttling bump since we have absolutely no way to know if yes or no we've access before making the call!

**Comment by brammator** [comment]
Okay, so maybe endpoint "post__do_i_have_access_to_this_location_ids" that simply returns "yes" or "no" instead of error?  And "no" would be sufficient even if there's no actual structure by that ID, so it won't be used for scraping.

Or, add "inaccessible" flag in asset list, that would be much more helpful.

But again, making discrepancy between in-game info and api is bad, and punishing app for this is just evil.  This could be easily exploitable to DDoS alliance automated tools.

**Comment by MrBMT** [comment]
> This is not an issue. This is functioning as designed. Game Design does not want us to have access to the names of structures that the character is not on the ACL for. It is just that plain and simple. You, the developer, regardless of whether or not the owner of the assets has given you permission to the view the assets, does not have access to the structure any more and therefore cannot resolve the name of the structure.

If that's the case, then why is that inconsistent with the in-game design?

For example, I have assets in a Keepstar that I no longer have access to on one of my accounts. I can see the structure details just fine through the assets window, and right click on the name and view further details.

![example](https://user-images.githubusercontent.com/6931281/39965799-ee8d3c4c-5697-11e8-8204-6985ac9fc304.png)

#643 - Great except we're not dealing with corporation assets, we're dealing with personal assets which that can not be used for.

#510 - Is about anonymous use of the endpoint, again, not what we're looking for.

#674 - Could be used for multiple malicious reasons. I'm not surprised they said no.

Either way, this is something we CCP feedback on, as they're the only ones that can actually do anything about this.

If they don't want to provide access to the structure details, then fine. However, in that case there are _still_ changes that need to be made as otherwise this can make the ESI API unusable.

In the situation that you're looking up structure information based on where multiple characters have assets there's no way to know if they do or do not have access to the structure before you send those requests.

If they don't, then sure, fine, send back a 403 Forbidden message. But instead _do not_ make it count against the ESI error limit, otherwise people can easily get locked out from sending more requests for _perfectly legitimate_ use of the API.

**Comment by SpeedProg** [comment]
> If that's the case, then why is that inconsistent with the in-game design?

> For example, I have assets in a Keepstar that I no longer have access to on one of my accounts. I can see the structure details just fine through the assets window, and right click on the name and view further details.

Because you are not allowed to automate the eve client, so you are comparing apples with oranges.

**Comment by ddavaham** [comment]
@warlof This feature request would answer the access issue. I haven't read it at just did a simple search of open issues for ACL

https://github.com/ccpgames/esi-issues/issues/55

Maybe ask for an update on it.

Another temp work around is just to display unknown structure and have a back ground process slowly work through unknown structures with random tokens trying to resolve them.

Back to this thread, for those that don't know, the reason this is such a sensitive topic is because we have been addressing it for almost, if not, an entire year. The structure name contains the system that the structure is in. The returned details contain the type of structure it is. If the API returned structure details JUST because you have assets in the structure (let's think about the load that would put on ESI rel quick figuring that out for you EVERY time you queried assets) what do you think a developer who get 100 tokens from 100 different character who each have assets in 100 different keepstars?

The reason that you can see the name in game is because you are the only one with access to that particular piece of information. You are the only one that knows that your assets are in that structure. You can't build a database of known structure locations with that information, well not programmatically. Through the API this would be possible, hence the stern response. Now the ACL issue that I linked earlier may very well be the answer to this problem, depends on how CCP addresses it. But I would stop hoping for some way to resolve structure names with a token that is not on the ACL for that structure because indoint, and personally hope, it'll ever happen. 

Sorry for the bad grammar if there is any. On my phone atm.

**Comment by Seavert** [comment]
Another contra: you can have items in several structures with identical type and name - which look the same in game, but would be distinguishable in API due to id.

**Comment by CarbonAlabel** [comment]
@ddavaham The traditional way for EVE players to get CCP to fix something is an universal and overwhelming show of outrage over it. This is what's happening here. It's a legitimate feature request, with a very much valid use case, and is in very high demand, even though some similar requests have previously been rejected due to what amounts to technical limitations.

I can't be sure what the motivation behind your "This is not an issue. This is functioning as designed." comment was, but the reason I downvoted it is because it sounded a lot like a "Fuck you for trying to make the API better." Keeping quiet about problems won't do anything to fix them.

**Comment by tsuthers-ccpgames** [comment]
I see that the previous answers have been linked, and I also see that this rapidly turning into a burning dumpster fire of a thread, so I'm going to close it.

**Comment by MrBMT** [comment]
@tsuthers-ccpgames Respecfully, this may be similar in some ways to previous issues, but it's actually a new one, as I pointed out in https://github.com/ccpgames/esi-issues/issues/916#issuecomment-388614125.

**Comment by warlof** [comment]
Returning a response in all case with a Unknown in name field is suitable I think.
Both `position` and `type_id` are already optional fields actually. Just have to turn `solar_system_id` as optional as well and we're going to something much more usable.

related to ccpgames/esi-issues#55 - you're assuming that the character owning asset in a location, is also granted to retrieve information from `/accesslits/` ?

Sounds like quite much complicated :/

**Comment by GoldenGnu** [comment]
Everyone should go upvote: https://github.com/ccpgames/esi-issues/issues/918
That have a real chance for being implemented, in contrast to this issue.
As it will not be scrap-able.

**Comment by brammator** [comment]
@Seavert that's not a "contra" because you already got these "different IDs" from assets endpoint.
