### ISSUE TITLE
Some form of permanent auth.

### ISSUE THREAD

**Issue by Ligraph** [ccpgames/esi-issues#99]
Since this api is SSO based (from what I've seen), it would be nice to have something permanent, like the XML API keys, since refresh tokens are getting reset periodically.

**Comment by Robbilie** [comment]
may i ask what you mean with "reset periodically"? iirc they only got reset once when ccp encountered a security issue…

**Comment by wtfrank** [comment]
Its not about access tokens vs refresh tokens is it?

**Comment by Ligraph** [comment]
> iirc they only got reset once when ccp encountered a security issue…

That's what I've heard too, but its often enough that it would be a pita if someone was using them for alliance/corp apis or something similar.  If the security issues clear up I don't see a reason for this, but if they don't it would be nice to have something that wouldn't need to get rest.

**Comment by Legedric** [comment]
There is already a permanent auth available through refresh tokens.
Whenever you auth a character and get a temporary access token (valid for 20 minutes) you also get a refresh token. You may use this refresh token to get a new access token (to be fully authenticated) every 20 minutes and you have what is similar to a permanent auth.

For example my site has a cronjob running every minute to refresh access tokens that are about to run out within the next 2 minutes. Pretty simple if you ask me ;)

It won't get more permanent than that...

**Comment by rottjr** [comment]
I agree, I have only had a refresh token go bad on me once.

 If you are really worried about it than if this happens just request alert the user that a security error was encountered and they need to re-authorize their EvE API, then redirect them to your SSO request page. Since the frequency of this seems to be limited to less than once a month it shouldn't be too annoying to the end user. 

However make sure to use the EvE Online user ID when connecting tables in a database such as connection to a cache table, this way if you need to create a new row with a different auto incremented ID the rows will still match regardless of the refresh token reset. This way if the user had any saved information that was specific to their EvE account it will still be available and the user will experience a 'seamless' transition back into the website/application.

Hope this help!
o7 Pizza Thief

**Comment by Legedric** [comment]
I know I am quite picky here but there is no such thing in EVE SSO as EVE Online user ID as the SSO is not able to show relationships between characters and accounts anymore (except the ownerHash).
So the characterID is what you want to use for SSO related stuff and tie that to whatever userID your project is using as a wraparound for it.

**Comment by Robbilie** [comment]
If i May be picky aswell, you dont always get a refreshtoken, implicit auth or auth without any scopes wont yield you a refreshtoken.

You have to take care of ppl revoking refresh tokens anyways so...

Also ccp should add an endpoint for deleting refresh tokens so apps can properly implement logout but that's a different story

We are using oauth, that's it.

**Comment by rottjr** [comment]
@Legedric you are absolutely right. There is no EVEO User ID, you get the character ID, I misspoke, thank you for correcting me.

@Robbilie you should not be requesting a public data only scope request via the Authenicated API Access using scopes. In the EVE SSO Developer API Application settings you have two choices of SSO Authentication, Authentication Only (use for only public data) and Authenticated API Access (use for scope access to private data). And you are very right, the program/application should have a catch for 'expired' SSO Tokens because they will likely act exactly like an expired token when revoked by the user via the EvE API Dashboard.

**Comment by a-tal** [comment]
refresh tokens are ~permanent. thanks everyone for chiming in
